# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.runs/synth_1/topLevel.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 1
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.cache/wt [current_project]
set_property parent.project_path /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty-a7-35:part0:1.1 [current_project]
set_property ip_output_repo /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/prim/primitives.v
set_property file_type "Verilog Header" [get_files /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/prim/primitives.v]
read_verilog -library xil_defaultlib {
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/prim/agu.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/prim/alu.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/prim/cmp.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/prim/cnn.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/controller/controller.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/controller/debug_controller.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/controller/decoder.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/prim/div.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/mem/dm_merge.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/mem/dm_wbb.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/controller/hazards.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/test_bench/jtag_interface.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/new/jtag_peripheral.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/test_bench/jtag_scan_register.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/test_bench/jtag_tap_controller.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/prim/lx.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/mem/mem_DMb.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/mem/mem_PMb.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/prim/mpy.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/mux/mux___X_x_w1_wad.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/mux/mux___pidTGT_w.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/mux/mux_aguB.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/mux/mux_aluA.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/mux/mux_aluB.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/mux/mux_dm_addr.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/mux/mux_dmb_wr.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/mux/mux_jmp_tgt_ID.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/mux/mux_mpyM.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/mux/mux_ocd_data_w.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/mux/mux_ocd_instr_w.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/mux/mux_ocd_swbreak.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/mux/mux_pcaA.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/mux/mux_pcaB.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/mux/mux_pm_addr.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/mux/mux_pm_wr.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/mux/mux_x_w1.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/mux/mux_x_w1_dead.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/prim/ocd_addr_incr.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/prim/pca.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/pipe/pipe___ocd_ld_DMbEX.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/pipe/pipe___ocd_ld_DMbS3.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/pipe/pipe___ocd_ld_PMbEX.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/pipe/pipe___ocd_ld_PMbS3.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/pipe/pipe___ocd_st_DMbEX.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/pipe/pipe___ocd_st_DMbS3.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/pipe/pipe___ocd_st_PMbEX.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/pipe/pipe___pidTGT.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/reg/reg_PC.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/reg/reg_PC_EX.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/reg/reg_PC_ID.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/reg/reg_X.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/reg/reg_ocd_addr.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/reg/reg_ocd_data.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/reg/reg_ocd_instr.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/imports/trv32p3_cnn/trv32p3_cnn.v
  /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/sources_1/new/topLevel.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/constrs_1/imports/digilent-xdc-master/Arty-A7-35-Master.xdc
set_property used_in_implementation false [get_files /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/constrs_1/imports/digilent-xdc-master/Arty-A7-35-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/elec/Thesis/trv32p3_cnn_Vivado/trv32p3_cnn_Vivado.srcs/utils_1/imports/synth_1/trv32p3_cnn.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top topLevel -part xc7a35ticsg324-1L
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef topLevel.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file topLevel_utilization_synth.rpt -pb topLevel_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
