
// File generated by Go version U-2022.12#33f3808fcb#221128, Thu Jan 25 16:08:15 2024
// Copyright 2014-2022 Synopsys, Inc. All rights reserved.
// go -I../lib -F -DSYNTHESIS_NO_UNGROUP -D__tct_patch__=0 -Verilog -otrv32p3_cnn_vlog -cgo_options.cfg -Itrv32p3_cnn_vlog/tmp_pdg -updg -updg_controller trv32p3_cnn



`timescale 1ns/1ps

// module decoder : decoder
module decoder
  ( input         reset,
    input         clock,
    input         hzd_stall_in,
    input         kill_ID_in,
    input         trn_ID_valid_in,
    input  [31:0] trn_IR_ID,
    output [34:0] EX_enabling_out,
    output [23:0] ID_enabling_out,
    output  [4:0] __X_x_r1_rad_out, // t5u
    output  [4:0] __X_x_r2_rad_out, // t5u
    output  [4:0] __X_x_r3_rad_out, // t5u
    output  [4:0] __X_x_w2_wad_out, // t5u
    output        issue_sig_out,
    output [31:0] reg_IR_EX_out,
    output [31:0] reg_IR_ID_out
  );


  localparam NOP = 32'b00000000000000000000000000110011;

  reg    [34:0] EX_enabling;
  wire   [23:0] ID_enabling;
  wire   internal_mc_stall;
  wire   new_mc_reg_val;
  reg    [34:0] predec_EX_enabling;
  reg    [23:0] predec_ID_enabling;
  reg    reg_ID_valid;
  reg    [31:0] reg_IR_EX;
  reg    [31:0] reg_IR_ID;
  wire   trn_EX_valid;

  reg en___X_x_r1_raddr_EX;
  reg [4:0] __X_x_r1_raddr_EX;
  reg [4:0] r___X_x_r1_raddr;
  reg en___X_x_r2_raddr_EX;
  reg [4:0] __X_x_r2_raddr_EX;
  reg [4:0] r___X_x_r2_raddr;
  reg en___X_x_r3_raddr_ID;
  reg [4:0] __X_x_r3_raddr_ID;
  reg en___X_x_r3_raddr_EX;
  reg [4:0] __X_x_r3_raddr_EX;
  reg [4:0] r___X_x_r3_raddr;
  reg en___X_x_w2_waddr_EX;
  reg [4:0] __X_x_w2_waddr_EX;
  reg [4:0] r___X_x_w2_waddr;
  // 20 register address bits

  function [2:0] decode_words (input [31:0]  ins);
    begin

      decode_words = 3'b000; // 1 word (default)
      if (
           ( ins[31:0] == 32'b00000000000100000010000001111011)                                                                             // 00000000000100000010000001111011
        || ( ins[31:25] == 7'b0000000 && ins[6] == 1'b0 && ins[4:3] == 2'b10 && ins[1:0] == 2'b11)                                          // 0000000xxxxxxxxxxxxxxxxxx0x10x11
        || ( ins[31:26] == 6'b000000 && ins[13] == 1'b1 && ins[6] == 1'b0 && ins[4:3] == 2'b10 && ins[1:0] == 2'b11)                        // 000000xxxxxxxxxxxx1xxxxxx0x10x11
        || ( ins[31:26] == 6'b000000 && ins[12] == 1'b0 && ins[6] == 1'b0 && ins[4:3] == 2'b10 && ins[1:0] == 2'b11)                        // 000000xxxxxxxxxxxxx0xxxxx0x10x11
        || ( ins[31:26] == 6'b000000 && ins[6:3] == 4'b0110 && ins[1:0] == 2'b11)                                                           // 000000xxxxxxxxxxxxxxxxxxx0110x11
        || ( ins[31] == 1'b0 && ins[29:25] == 5'b00000 && ins[14:12] == 3'b000 && ins[6] == 1'b0 && ins[4:3] == 2'b10 && ins[1:0] == 2'b11) // 0x00000xxxxxxxxxx000xxxxx0x10x11
        || ( ins[31] == 1'b0 && ins[29:25] == 5'b00000 && ins[14:12] == 3'b101 && ins[6] == 1'b0 && ins[4:3] == 2'b10 && ins[1:0] == 2'b11) // 0x00000xxxxxxxxxx101xxxxx0x10x11
        || ( ins[31:25] == 7'b1100000 && ins[14:12] == 3'b001 && ins[6:3] == 4'b0110 && ins[1:0] == 2'b11)                                  // 1100000xxxxxxxxxx001xxxxx0110x11
        || ( ins[14:12] == 3'b000 && ins[6:3] == 4'b1100 && ins[1:0] == 2'b11)                                                              // xxxxxxxxxxxxxxxxx000xxxxx1100x11
        || ( ins[14:13] == 2'b00 && ins[6] == 1'b0 && ins[4:0] == 5'b00011)                                                                 // xxxxxxxxxxxxxxxxx00xxxxxx0x00011
        || ( ins[14] == 1'b0 && ins[12] == 1'b0 && ins[6] == 1'b0 && ins[4:0] == 5'b00011)                                                  // xxxxxxxxxxxxxxxxx0x0xxxxx0x00011
        || ( ins[14] == 1'b1 && ins[6:0] == 7'b1100011)                                                                                     // xxxxxxxxxxxxxxxxx1xxxxxxx1100011
        || ( ins[13] == 1'b0 && ins[6:0] == 7'b0000011)                                                                                     // xxxxxxxxxxxxxxxxxx0xxxxxx0000011
        || ( ins[13] == 1'b0 && ins[6:0] == 7'b1100011)                                                                                     // xxxxxxxxxxxxxxxxxx0xxxxxx1100011
        || ( ins[13] == 1'b1 && ins[6:3] == 4'b0010 && ins[1:0] == 2'b11)                                                                   // xxxxxxxxxxxxxxxxxx1xxxxxx0010x11
        || ( ins[12] == 1'b0 && ins[6:3] == 4'b0010 && ins[1:0] == 2'b11)                                                                   // xxxxxxxxxxxxxxxxxxx0xxxxx0010x11
        || ( ins[6] == 1'b0 && ins[4:0] == 5'b10111)                                                                                        // xxxxxxxxxxxxxxxxxxxxxxxxx0x10111
        || ( ins[6:0] == 7'b1101111)                                                                                                        // xxxxxxxxxxxxxxxxxxxxxxxxx1101111
         )
      begin
        decode_words = 3'b111; // 4 words
      end
    end
  endfunction

  function [0:0] decode_cycles (input [31:0]  ins);
    begin

      decode_cycles = 1'b0; // 1 cycle (default)
      if (
           ( ins[31:0] == 32'b00000000000100000010000001111011)                     // 00000000000100000010000001111011
        || ( ins[31:25] == 7'b0000001 && ins[14] == 1'b1 && ins[6:0] == 7'b0110011) // 0000001xxxxxxxxxx1xxxxxxx0110011
        || ( ins[14:12] == 3'b000 && ins[6:4] == 3'b110 && ins[2:0] == 3'b111)      // xxxxxxxxxxxxxxxxx000xxxxx110x111
        || ( ins[6:0] == 7'b1101111)                                                // xxxxxxxxxxxxxxxxxxxxxxxxx1101111
         )
      begin
        decode_cycles = 1'b1; // 2 cycles
      end
    end
  endfunction

  assign ID_enabling_out = ID_enabling;
  assign EX_enabling_out = EX_enabling;

  assign reg_IR_EX_out = reg_IR_EX;
  assign reg_IR_ID_out = reg_IR_ID;

  assign issue_sig_out = !internal_mc_stall;
  assign internal_mc_stall = new_mc_reg_val;
  assign new_mc_reg_val = (reg_ID_valid) ? decode_cycles(reg_IR_ID) : 1'b0;

  always @ (*)
  begin : decode_ID
    reg en_pca_ohe_sel_ID;
    reg en_agu_ohe_sel_ID;
    reg [1:0] en_controller_bin_sel_ID;
    reg en_reg_PC_EX_ohe_sel_ID;
    reg [2:0] en_mem_DMb_bin_sel_ID;
    reg en_mux_dm_addr_ohe_sel_ID;
    reg en_mux_pcaA_ohe_sel_ID;
    reg [1:0] en_mux_pcaB_bin_sel_ID;
    reg en_mux_jmp_tgt_ID_ohe_sel_ID;
    reg [1:0] en_mux_aguB_bin_sel_ID;
    reg en_mux___pidTGT_w_ohe_sel_ID;
    reg [7:0] en_hazards_decode_ID;


    en___X_x_r3_raddr_ID = 0;
    __X_x_r3_raddr_ID = 0;

    en_pca_ohe_sel_ID = 0;            // pca
    en_agu_ohe_sel_ID = 0;            // agu
    en_controller_bin_sel_ID = 0;     // controller
    en_reg_PC_EX_ohe_sel_ID = 0;      // reg_PC_EX
    en_mem_DMb_bin_sel_ID = 0;        // mem_DMb
    en_mux_dm_addr_ohe_sel_ID = 0;    // mux_dm_addr
    en_mux_pcaA_ohe_sel_ID = 0;       // mux_pcaA
    en_mux_pcaB_bin_sel_ID = 0;       // mux_pcaB
    en_mux_jmp_tgt_ID_ohe_sel_ID = 0; // mux_jmp_tgt_ID
    en_mux_aguB_bin_sel_ID = 0;       // mux_aguB
    en_mux___pidTGT_w_ohe_sel_ID = 0; // mux___pidTGT_w
    en_hazards_decode_ID = 0;         // hazards

    if (reg_ID_valid)
    begin
      if (
           ( reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[6:0] == 7'b1100111)                                           // xxxxxxxxxxxxxxxxx000xxxxx1100111
        || ( reg_IR_ID[14:13] == 2'b00 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b00011)                      // xxxxxxxxxxxxxxxxx00xxxxxx0x00011
        || ( reg_IR_ID[14] == 1'b0 && reg_IR_ID[12] == 1'b0 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b00011) // xxxxxxxxxxxxxxxxx0x0xxxxx0x00011
        || ( reg_IR_ID[13] == 1'b0 && reg_IR_ID[6:0] == 7'b0000011)                                                // xxxxxxxxxxxxxxxxxx0xxxxxx0000011
         )
      begin
        en___X_x_r3_raddr_ID = 1'b1;
        __X_x_r3_raddr_ID = reg_IR_ID[19:15]; // __X_x_r3_raddr_cp___CTt5u_cstP15_ID_ID [ldst.n:54][ldst.n:91][ctrl.n:189](regX.n:89)
        en_hazards_decode_ID[1] = 1'b1;       // read_after_divHWraw2ndID  t5u_cstP15_ID[ldst.n:54][ldst.n:91][ctrl.n:189]
                                              // agu_read_after_writeHWraw2ndID  t5u_cstP15_ID[ldst.n:54][ldst.n:91][ctrl.n:189]
      end
      if (
           ( reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[6:3] == 4'b1100 && reg_IR_ID[1:0] == 2'b11) // xxxxxxxxxxxxxxxxx000xxxxx1100x11
        || ( reg_IR_ID[14] == 1'b1 && reg_IR_ID[6:0] == 7'b1100011)                              // xxxxxxxxxxxxxxxxx1xxxxxxx1100011
        || ( reg_IR_ID[13] == 1'b0 && reg_IR_ID[6:0] == 7'b1100011)                              // xxxxxxxxxxxxxxxxxx0xxxxxx1100011
        || ( reg_IR_ID[6:0] == 7'b1101111)                                                       // xxxxxxxxxxxxxxxxxxxxxxxxx1101111
         )
      begin
        en_pca_ohe_sel_ID = 1'b1; // pcaR_add_pcaA_pcaB_pca_ID [ctrl.n:112][ctrl.n:163][ctrl.n:192]
      end
      if (
           ( reg_IR_ID[14:13] == 2'b00 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b00011)                      // xxxxxxxxxxxxxxxxx00xxxxxx0x00011
        || ( reg_IR_ID[14] == 1'b0 && reg_IR_ID[12] == 1'b0 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b00011) // xxxxxxxxxxxxxxxxx0x0xxxxx0x00011
        || ( reg_IR_ID[13] == 1'b0 && reg_IR_ID[6:0] == 7'b0000011)                                                // xxxxxxxxxxxxxxxxxx0xxxxxx0000011
         )
      begin
        en_agu_ohe_sel_ID = 1'b1;         // aguR_add_aguA_aguB_agu_ID [ldst.n:57][ldst.n:94]
        en_mux_dm_addr_ohe_sel_ID = 1'b1; // dm_addr_copy0_aguR_ID [ldst.n:58][ldst.n:95]
      end
      if (
           ( reg_IR_ID[6:0] == 7'b1101111) // xxxxxxxxxxxxxxxxxxxxxxxxx1101111
         )
      begin
        en_controller_bin_sel_ID = 2'b01;    // lnk_id_jal_of21_ID [ctrl.n:154]
        en_mux_jmp_tgt_ID_ohe_sel_ID = 1'b1; // jmp_tgt_ID_copy0_pcaR_ID [ctrl.n:165]
      end
      if (
           ( reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[6:0] == 7'b1100111) // xxxxxxxxxxxxxxxxx000xxxxx1100111
         )
      begin
        en_controller_bin_sel_ID = 2'b10; // lnk_id_jalr_trgt_ID [ctrl.n:193]
        en_mux_pcaA_ohe_sel_ID = 1'b1;    // pcaA_copy0_x_r3_ID [ctrl.n:189](regX.n:89)
        en_mux_pcaB_bin_sel_ID = 2'b01;   // pcaB_copy0___CTt12s_cstP20_ID [ctrl.n:190]
        en_hazards_decode_ID[0] = 1'b1;   // jalr_readHWraw2ndID  t5u_cstP15_ID[ctrl.n:189]
      end
      if (
           ( reg_IR_ID[6:0] == 7'b0010111) // xxxxxxxxxxxxxxxxxxxxxxxxx0010111
         )
      begin
        en_reg_PC_EX_ohe_sel_ID = 1'b1; // PC_EX_wr_PC_EX_w_ID [alu.n:209]
      end
      if (
           ( reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[6:0] == 7'b0100011) // xxxxxxxxxxxxxxxxx000xxxxx0100011
         )
      begin
        en_mem_DMb_bin_sel_ID = 3'b001; // mem_enab_DMb_st_dmb_wr_dm_addr_ID [ldst.n:99]
                                        // cp_extad_DMb_st_dmb_wr_dm_addr_ID [ldst.n:99]
      end
      if (
           ( reg_IR_ID[14:12] == 3'b001 && reg_IR_ID[6:0] == 7'b0100011) // xxxxxxxxxxxxxxxxx001xxxxx0100011
         )
      begin
        en_mem_DMb_bin_sel_ID = 3'b010; // mem_enab_DMh_st_dmh_wr_dm_addr_ID [ldst.n:100]
                                        // cp_extad_DMh_st_dmh_wr_dm_addr_ID [ldst.n:100]
      end
      if (
           ( reg_IR_ID[14:12] == 3'b010 && reg_IR_ID[6:0] == 7'b0100011) // xxxxxxxxxxxxxxxxx010xxxxx0100011
         )
      begin
        en_mem_DMb_bin_sel_ID = 3'b011; // mem_enab_DMw_st_dmw_wr_dm_addr_ID [ldst.n:101]
                                        // cp_extad_DMw_st_dmw_wr_dm_addr_ID [ldst.n:101]
      end
      if (
           ( reg_IR_ID[13:12] == 2'b00 && reg_IR_ID[6:0] == 7'b0000011) // xxxxxxxxxxxxxxxxxx00xxxxx0000011
         )
      begin
        en_mem_DMb_bin_sel_ID = 3'b100; // mem_enab_dmb_rd_ld_DMb_dm_addr_ID [ldst.n:62]
                                        // cp_extad_dmb_rd_ld_DMb_dm_addr_ID [ldst.n:62]
      end
      if (
           ( reg_IR_ID[13:12] == 2'b01 && reg_IR_ID[6:0] == 7'b0000011) // xxxxxxxxxxxxxxxxxx01xxxxx0000011
         )
      begin
        en_mem_DMb_bin_sel_ID = 3'b101; // mem_enab_dmh_rd_ld_DMh_dm_addr_ID [ldst.n:63]
                                        // cp_extad_dmh_rd_ld_DMh_dm_addr_ID [ldst.n:63]
      end
      if (
           ( reg_IR_ID[14:12] == 3'b010 && reg_IR_ID[6:0] == 7'b0000011) // xxxxxxxxxxxxxxxxx010xxxxx0000011
         )
      begin
        en_mem_DMb_bin_sel_ID = 3'b110; // mem_enab_dmw_rd_ld_DMw_dm_addr_ID [ldst.n:64]
                                        // cp_extad_dmw_rd_ld_DMw_dm_addr_ID [ldst.n:64]
      end
      if (
           ( reg_IR_ID[14] == 1'b1 && reg_IR_ID[6:0] == 7'b1100011) // xxxxxxxxxxxxxxxxx1xxxxxxx1100011
        || ( reg_IR_ID[13] == 1'b0 && reg_IR_ID[6:0] == 7'b1100011) // xxxxxxxxxxxxxxxxxx0xxxxxx1100011
         )
      begin
        en_mux_pcaB_bin_sel_ID = 2'b10;      // pcaB_copy0___CTt13s_s2_cstP31_12P7_11P25_10_5P8_4_1_ID [ctrl.n:110]
        en_mux___pidTGT_w_ohe_sel_ID = 1'b1; // pidTGT_copy0_pcaR_ID [ctrl.n:114]
      end
      if (
           ( reg_IR_ID[14] == 1'b0 && reg_IR_ID[12] == 1'b0 && reg_IR_ID[6:0] == 7'b0000011) // xxxxxxxxxxxxxxxxx0x0xxxxx0000011
        || ( reg_IR_ID[13] == 1'b0 && reg_IR_ID[6:0] == 7'b0000011)                          // xxxxxxxxxxxxxxxxxx0xxxxxx0000011
         )
      begin
        en_mux_aguB_bin_sel_ID = 2'b01; // aguB_copy0___CTt12s_cstP20_ID [ldst.n:55]
      end
      if (
           ( reg_IR_ID[14:13] == 2'b00 && reg_IR_ID[6:0] == 7'b0100011)                      // xxxxxxxxxxxxxxxxx00xxxxxx0100011
        || ( reg_IR_ID[14] == 1'b0 && reg_IR_ID[12] == 1'b0 && reg_IR_ID[6:0] == 7'b0100011) // xxxxxxxxxxxxxxxxx0x0xxxxx0100011
         )
      begin
        en_mux_aguB_bin_sel_ID = 2'b10; // aguB_copy0___CTt12s_cstP25_11_5P7_4_0_ID [ldst.n:92]
      end
      if (
           ( reg_IR_ID[31:25] == 7'b0000000 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b10011)                                                      // 0000000xxxxxxxxxxxxxxxxxx0x10011
        || ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[13] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b10011)                              // 000000xxxxxxxxxxxx1xxxxxx0x10011
        || ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[12] == 1'b0 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b10011)                              // 000000xxxxxxxxxxxxx0xxxxx0x10011
        || ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[6:0] == 7'b0110011)                                                                             // 000000xxxxxxxxxxxxxxxxxxx0110011
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b10011) // 0x00000xxxxxxxxxx000xxxxx0x10011
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:12] == 3'b101 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b10011) // 0x00000xxxxxxxxxx101xxxxx0x10011
        || ( reg_IR_ID[31:25] == 7'b1100000 && reg_IR_ID[14:12] == 3'b001 && reg_IR_ID[6:0] == 7'b0110011)                                              // 1100000xxxxxxxxxx001xxxxx0110011
        || ( reg_IR_ID[14] == 1'b1 && reg_IR_ID[6:0] == 7'b1100011)                                                                                     // xxxxxxxxxxxxxxxxx1xxxxxxx1100011
        || ( reg_IR_ID[13] == 1'b0 && reg_IR_ID[6:0] == 7'b1100011)                                                                                     // xxxxxxxxxxxxxxxxxx0xxxxxx1100011
        || ( reg_IR_ID[13] == 1'b1 && reg_IR_ID[6:0] == 7'b0010011)                                                                                     // xxxxxxxxxxxxxxxxxx1xxxxxx0010011
        || ( reg_IR_ID[12] == 1'b0 && reg_IR_ID[6:0] == 7'b0010011)                                                                                     // xxxxxxxxxxxxxxxxxxx0xxxxx0010011
         )
      begin
        en_hazards_decode_ID[2] = 1'b1; // read_after_div_1HWraw2ndID  t5u_cstP15_EX[alu.n:69][alu.n:131][alu.n:167][mpy.n:61][div.n:58][ctrl.n:94][cnn.n:26]
      end
      if (
           ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[6:0] == 7'b0110011)                                                                               // 000000xxxxxxxxxxxxxxxxxxx0110011
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[6:5] == 2'b01 && reg_IR_ID[3:0] == 4'b0011) // 0x00000xxxxxxxxxx000xxxxx01x0011
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:12] == 3'b101 && reg_IR_ID[6:0] == 7'b0110011)                         // 0x00000xxxxxxxxxx101xxxxx0110011
        || ( reg_IR_ID[31:25] == 7'b1100000 && reg_IR_ID[14:12] == 3'b001 && reg_IR_ID[6:5] == 2'b01 && reg_IR_ID[3:0] == 4'b0011)                        // 1100000xxxxxxxxxx001xxxxx01x0011
        || ( reg_IR_ID[14:13] == 2'b00 && reg_IR_ID[5:0] == 6'b100011)                                                                                    // xxxxxxxxxxxxxxxxx00xxxxxxx100011
        || ( reg_IR_ID[14] == 1'b0 && reg_IR_ID[12] == 1'b0 && reg_IR_ID[6:0] == 7'b0100011)                                                              // xxxxxxxxxxxxxxxxx0x0xxxxx0100011
        || ( reg_IR_ID[14] == 1'b1 && reg_IR_ID[6:0] == 7'b1100011)                                                                                       // xxxxxxxxxxxxxxxxx1xxxxxxx1100011
        || ( reg_IR_ID[13] == 1'b0 && reg_IR_ID[6:0] == 7'b1100011)                                                                                       // xxxxxxxxxxxxxxxxxx0xxxxxx1100011
         )
      begin
        en_hazards_decode_ID[3] = 1'b1; // read_after_div_1HWraw2nd1ID  t5u_cstP20_EX[alu.n:70][mpy.n:62][div.n:59][ldst.n:99][ldst.n:100][ldst.n:101][ctrl.n:95][cnn.n:27]
      end
      if (
           ( reg_IR_ID[31:25] == 7'b1100000 && reg_IR_ID[14:12] == 3'b001 && reg_IR_ID[6:0] == 7'b0110011) // 1100000xxxxxxxxxx001xxxxx0110011
         )
      begin
        en_hazards_decode_ID[4] = 1'b1; // read_after_div_1HWraw2nd2ID  t5u_cstP7_EX[cnn.n:28]
      end
      if (
           ( reg_IR_ID[31:25] == 7'b0000000 && reg_IR_ID[11] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                                                      // 0000000xxxxxxxxxxxxx1xxxx0x10x11
        || ( reg_IR_ID[31:25] == 7'b0000000 && reg_IR_ID[10] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                                                      // 0000000xxxxxxxxxxxxxx1xxx0x10x11
        || ( reg_IR_ID[31:25] == 7'b0000000 && reg_IR_ID[9] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                                                       // 0000000xxxxxxxxxxxxxxx1xx0x10x11
        || ( reg_IR_ID[31:25] == 7'b0000000 && reg_IR_ID[8] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                                                       // 0000000xxxxxxxxxxxxxxxx1x0x10x11
        || ( reg_IR_ID[31:25] == 7'b0000000 && reg_IR_ID[7:6] == 2'b10 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                                                                            // 0000000xxxxxxxxxxxxxxxxx10x10x11
        || ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[14:13] == 2'b01 && reg_IR_ID[11] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                          // 000000xxxxxxxxxxx01x1xxxx0x10x11
        || ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[14:13] == 2'b01 && reg_IR_ID[10] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                          // 000000xxxxxxxxxxx01xx1xxx0x10x11
        || ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[14:13] == 2'b01 && reg_IR_ID[9] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                           // 000000xxxxxxxxxxx01xxx1xx0x10x11
        || ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[14:13] == 2'b01 && reg_IR_ID[8] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                           // 000000xxxxxxxxxxx01xxxx1x0x10x11
        || ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[14:13] == 2'b01 && reg_IR_ID[7:6] == 2'b10 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                                                // 000000xxxxxxxxxxx01xxxxx10x10x11
        || ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[14] == 1'b0 && reg_IR_ID[11] == 1'b1 && reg_IR_ID[6:3] == 4'b0110 && reg_IR_ID[1:0] == 2'b11)                                                    // 000000xxxxxxxxxxx0xx1xxxx0110x11
        || ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[14] == 1'b0 && reg_IR_ID[10] == 1'b1 && reg_IR_ID[6:3] == 4'b0110 && reg_IR_ID[1:0] == 2'b11)                                                    // 000000xxxxxxxxxxx0xxx1xxx0110x11
        || ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[14] == 1'b0 && reg_IR_ID[9] == 1'b1 && reg_IR_ID[6:3] == 4'b0110 && reg_IR_ID[1:0] == 2'b11)                                                     // 000000xxxxxxxxxxx0xxxx1xx0110x11
        || ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[14] == 1'b0 && reg_IR_ID[8] == 1'b1 && reg_IR_ID[6:3] == 4'b0110 && reg_IR_ID[1:0] == 2'b11)                                                     // 000000xxxxxxxxxxx0xxxxx1x0110x11
        || ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[14] == 1'b0 && reg_IR_ID[7:3] == 5'b10110 && reg_IR_ID[1:0] == 2'b11)                                                                            // 000000xxxxxxxxxxx0xxxxxx10110x11
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:11] == 4'b0001 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                         // 0x00000xxxxxxxxxx0001xxxx0x10x11
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[10] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11) // 0x00000xxxxxxxxxx000x1xxx0x10x11
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[9] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)  // 0x00000xxxxxxxxxx000xx1xx0x10x11
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[8] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)  // 0x00000xxxxxxxxxx000xxx1x0x10x11
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[7:6] == 2'b10 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                       // 0x00000xxxxxxxxxx000xxxx10x10x11
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:11] == 4'b1011 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                         // 0x00000xxxxxxxxxx1011xxxx0x10x11
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:12] == 3'b101 && reg_IR_ID[10] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11) // 0x00000xxxxxxxxxx101x1xxx0x10x11
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:12] == 3'b101 && reg_IR_ID[9] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)  // 0x00000xxxxxxxxxx101xx1xx0x10x11
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:12] == 3'b101 && reg_IR_ID[8] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)  // 0x00000xxxxxxxxxx101xxx1x0x10x11
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:12] == 3'b101 && reg_IR_ID[7:6] == 2'b10 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                       // 0x00000xxxxxxxxxx101xxxx10x10x11
        || ( reg_IR_ID[31:25] == 7'b1100000 && reg_IR_ID[14:11] == 4'b0011 && reg_IR_ID[6:3] == 4'b0110 && reg_IR_ID[1:0] == 2'b11)                                                                      // 1100000xxxxxxxxxx0011xxxx0110x11
        || ( reg_IR_ID[31:25] == 7'b1100000 && reg_IR_ID[14:12] == 3'b001 && reg_IR_ID[10] == 1'b1 && reg_IR_ID[6:3] == 4'b0110 && reg_IR_ID[1:0] == 2'b11)                                              // 1100000xxxxxxxxxx001x1xxx0110x11
        || ( reg_IR_ID[31:25] == 7'b1100000 && reg_IR_ID[14:12] == 3'b001 && reg_IR_ID[9] == 1'b1 && reg_IR_ID[6:3] == 4'b0110 && reg_IR_ID[1:0] == 2'b11)                                               // 1100000xxxxxxxxxx001xx1xx0110x11
        || ( reg_IR_ID[31:25] == 7'b1100000 && reg_IR_ID[14:12] == 3'b001 && reg_IR_ID[8] == 1'b1 && reg_IR_ID[6:3] == 4'b0110 && reg_IR_ID[1:0] == 2'b11)                                               // 1100000xxxxxxxxxx001xxx1x0110x11
        || ( reg_IR_ID[31:25] == 7'b1100000 && reg_IR_ID[14:12] == 3'b001 && reg_IR_ID[7:3] == 5'b10110 && reg_IR_ID[1:0] == 2'b11)                                                                      // 1100000xxxxxxxxxx001xxxx10110x11
        || ( reg_IR_ID[14:11] == 4'b0001 && reg_IR_ID[6:4] == 3'b110 && reg_IR_ID[2:0] == 3'b111)                                                                                                        // xxxxxxxxxxxxxxxxx0001xxxx110x111
        || ( reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[10] == 1'b1 && reg_IR_ID[6:4] == 3'b110 && reg_IR_ID[2:0] == 3'b111)                                                                                // xxxxxxxxxxxxxxxxx000x1xxx110x111
        || ( reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[9] == 1'b1 && reg_IR_ID[6:4] == 3'b110 && reg_IR_ID[2:0] == 3'b111)                                                                                 // xxxxxxxxxxxxxxxxx000xx1xx110x111
        || ( reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[8] == 1'b1 && reg_IR_ID[6:4] == 3'b110 && reg_IR_ID[2:0] == 3'b111)                                                                                 // xxxxxxxxxxxxxxxxx000xxx1x110x111
        || ( reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[7:4] == 4'b1110 && reg_IR_ID[2:0] == 3'b111)                                                                                                        // xxxxxxxxxxxxxxxxx000xxxx1110x111
        || ( reg_IR_ID[14] == 1'b0 && reg_IR_ID[12:11] == 2'b01 && reg_IR_ID[6:5] == 2'b00 && reg_IR_ID[3:0] == 4'b0011)                                                                                 // xxxxxxxxxxxxxxxxx0x01xxxx00x0011
        || ( reg_IR_ID[14] == 1'b0 && reg_IR_ID[12] == 1'b0 && reg_IR_ID[10] == 1'b1 && reg_IR_ID[6:5] == 2'b00 && reg_IR_ID[3:0] == 4'b0011)                                                            // xxxxxxxxxxxxxxxxx0x0x1xxx00x0011
        || ( reg_IR_ID[14] == 1'b0 && reg_IR_ID[12] == 1'b0 && reg_IR_ID[9] == 1'b1 && reg_IR_ID[6:5] == 2'b00 && reg_IR_ID[3:0] == 4'b0011)                                                             // xxxxxxxxxxxxxxxxx0x0xx1xx00x0011
        || ( reg_IR_ID[14] == 1'b0 && reg_IR_ID[12] == 1'b0 && reg_IR_ID[8] == 1'b1 && reg_IR_ID[6:5] == 2'b00 && reg_IR_ID[3:0] == 4'b0011)                                                             // xxxxxxxxxxxxxxxxx0x0xxx1x00x0011
        || ( reg_IR_ID[14] == 1'b0 && reg_IR_ID[12] == 1'b0 && reg_IR_ID[7:5] == 3'b100 && reg_IR_ID[3:0] == 4'b0011)                                                                                    // xxxxxxxxxxxxxxxxx0x0xxxx100x0011
        || ( reg_IR_ID[13] == 1'b0 && reg_IR_ID[11] == 1'b1 && reg_IR_ID[6:0] == 7'b0000011)                                                                                                             // xxxxxxxxxxxxxxxxxx0x1xxxx0000011
        || ( reg_IR_ID[13] == 1'b0 && reg_IR_ID[10] == 1'b1 && reg_IR_ID[6:0] == 7'b0000011)                                                                                                             // xxxxxxxxxxxxxxxxxx0xx1xxx0000011
        || ( reg_IR_ID[13] == 1'b0 && reg_IR_ID[9] == 1'b1 && reg_IR_ID[6:0] == 7'b0000011)                                                                                                              // xxxxxxxxxxxxxxxxxx0xxx1xx0000011
        || ( reg_IR_ID[13] == 1'b0 && reg_IR_ID[8] == 1'b1 && reg_IR_ID[6:0] == 7'b0000011)                                                                                                              // xxxxxxxxxxxxxxxxxx0xxxx1x0000011
        || ( reg_IR_ID[13] == 1'b0 && reg_IR_ID[7:0] == 8'b10000011)                                                                                                                                     // xxxxxxxxxxxxxxxxxx0xxxxx10000011
        || ( reg_IR_ID[13] == 1'b1 && reg_IR_ID[11] == 1'b1 && reg_IR_ID[6:3] == 4'b0010 && reg_IR_ID[1:0] == 2'b11)                                                                                     // xxxxxxxxxxxxxxxxxx1x1xxxx0010x11
        || ( reg_IR_ID[13] == 1'b1 && reg_IR_ID[10] == 1'b1 && reg_IR_ID[6:3] == 4'b0010 && reg_IR_ID[1:0] == 2'b11)                                                                                     // xxxxxxxxxxxxxxxxxx1xx1xxx0010x11
        || ( reg_IR_ID[13] == 1'b1 && reg_IR_ID[9] == 1'b1 && reg_IR_ID[6:3] == 4'b0010 && reg_IR_ID[1:0] == 2'b11)                                                                                      // xxxxxxxxxxxxxxxxxx1xxx1xx0010x11
        || ( reg_IR_ID[13] == 1'b1 && reg_IR_ID[8] == 1'b1 && reg_IR_ID[6:3] == 4'b0010 && reg_IR_ID[1:0] == 2'b11)                                                                                      // xxxxxxxxxxxxxxxxxx1xxxx1x0010x11
        || ( reg_IR_ID[13] == 1'b1 && reg_IR_ID[7:3] == 5'b10010 && reg_IR_ID[1:0] == 2'b11)                                                                                                             // xxxxxxxxxxxxxxxxxx1xxxxx10010x11
        || ( reg_IR_ID[12:11] == 2'b01 && reg_IR_ID[6:3] == 4'b0010 && reg_IR_ID[1:0] == 2'b11)                                                                                                          // xxxxxxxxxxxxxxxxxxx01xxxx0010x11
        || ( reg_IR_ID[12] == 1'b0 && reg_IR_ID[10] == 1'b1 && reg_IR_ID[6:3] == 4'b0010 && reg_IR_ID[1:0] == 2'b11)                                                                                     // xxxxxxxxxxxxxxxxxxx0x1xxx0010x11
        || ( reg_IR_ID[12] == 1'b0 && reg_IR_ID[9] == 1'b1 && reg_IR_ID[6:3] == 4'b0010 && reg_IR_ID[1:0] == 2'b11)                                                                                      // xxxxxxxxxxxxxxxxxxx0xx1xx0010x11
        || ( reg_IR_ID[12] == 1'b0 && reg_IR_ID[8] == 1'b1 && reg_IR_ID[6:3] == 4'b0010 && reg_IR_ID[1:0] == 2'b11)                                                                                      // xxxxxxxxxxxxxxxxxxx0xxx1x0010x11
        || ( reg_IR_ID[12] == 1'b0 && reg_IR_ID[7:3] == 5'b10010 && reg_IR_ID[1:0] == 2'b11)                                                                                                             // xxxxxxxxxxxxxxxxxxx0xxxx10010x11
        || ( reg_IR_ID[11] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b10111)                                                                                                                // xxxxxxxxxxxxxxxxxxxx1xxxx0x10111
        || ( reg_IR_ID[11] == 1'b1 && reg_IR_ID[6:0] == 7'b1101111)                                                                                                                                      // xxxxxxxxxxxxxxxxxxxx1xxxx1101111
        || ( reg_IR_ID[10] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b10111)                                                                                                                // xxxxxxxxxxxxxxxxxxxxx1xxx0x10111
        || ( reg_IR_ID[10] == 1'b1 && reg_IR_ID[6:0] == 7'b1101111)                                                                                                                                      // xxxxxxxxxxxxxxxxxxxxx1xxx1101111
        || ( reg_IR_ID[9] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b10111)                                                                                                                 // xxxxxxxxxxxxxxxxxxxxxx1xx0x10111
        || ( reg_IR_ID[9] == 1'b1 && reg_IR_ID[6:0] == 7'b1101111)                                                                                                                                       // xxxxxxxxxxxxxxxxxxxxxx1xx1101111
        || ( reg_IR_ID[8] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b10111)                                                                                                                 // xxxxxxxxxxxxxxxxxxxxxxx1x0x10111
        || ( reg_IR_ID[8] == 1'b1 && reg_IR_ID[6:0] == 7'b1101111)                                                                                                                                       // xxxxxxxxxxxxxxxxxxxxxxx1x1101111
        || ( reg_IR_ID[7:6] == 2'b10 && reg_IR_ID[4:0] == 5'b10111)                                                                                                                                      // xxxxxxxxxxxxxxxxxxxxxxxx10x10111
        || ( reg_IR_ID[7:0] == 8'b11101111)                                                                                                                                                              // xxxxxxxxxxxxxxxxxxxxxxxx11101111
         )
      begin
        en_hazards_decode_ID[5] = 1'b1; // write_after_divHWwaw2ndID  t5u_cstP7_EX[regX.n:99][cnn.n:35]
      end
      if (
           ( reg_IR_ID[31:25] == 7'b0000001 && reg_IR_ID[14] == 1'b1 && reg_IR_ID[6:0] == 7'b0110011) // 0000001xxxxxxxxxx1xxxxxxx0110011
         )
      begin
        en_hazards_decode_ID[6] = 1'b1; // div_busyHWnoDep2ndID
      end
      if (
           ( reg_IR_ID[31:25] == 7'b0000000 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                                                      // 0000000xxxxxxxxxxxxxxxxxx0x10x11
        || ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[14:13] == 2'b01 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                          // 000000xxxxxxxxxxx01xxxxxx0x10x11
        || ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[14] == 1'b0 && reg_IR_ID[6:3] == 4'b0110 && reg_IR_ID[1:0] == 2'b11)                                                    // 000000xxxxxxxxxxx0xxxxxxx0110x11
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11) // 0x00000xxxxxxxxxx000xxxxx0x10x11
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:12] == 3'b101 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11) // 0x00000xxxxxxxxxx101xxxxx0x10x11
        || ( reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[6:4] == 3'b110 && reg_IR_ID[2:0] == 3'b111)                                                                                // xxxxxxxxxxxxxxxxx000xxxxx110x111
        || ( reg_IR_ID[14] == 1'b0 && reg_IR_ID[12] == 1'b0 && reg_IR_ID[6:5] == 2'b00 && reg_IR_ID[3:0] == 4'b0011)                                                            // xxxxxxxxxxxxxxxxx0x0xxxxx00x0011
        || ( reg_IR_ID[13] == 1'b0 && reg_IR_ID[6:0] == 7'b0000011)                                                                                                             // xxxxxxxxxxxxxxxxxx0xxxxxx0000011
        || ( reg_IR_ID[13] == 1'b1 && reg_IR_ID[6:3] == 4'b0010 && reg_IR_ID[1:0] == 2'b11)                                                                                     // xxxxxxxxxxxxxxxxxx1xxxxxx0010x11
        || ( reg_IR_ID[12] == 1'b0 && reg_IR_ID[6:3] == 4'b0010 && reg_IR_ID[1:0] == 2'b11)                                                                                     // xxxxxxxxxxxxxxxxxxx0xxxxx0010x11
        || ( reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b10111)                                                                                                                // xxxxxxxxxxxxxxxxxxxxxxxxx0x10111
        || ( reg_IR_ID[6:0] == 7'b1101111)                                                                                                                                      // xxxxxxxxxxxxxxxxxxxxxxxxx1101111
         )
      begin
        en_hazards_decode_ID[7] = 1'b1; // div_wpHWnoDep2ndID
      end
    end
    if (hzd_stall_in)
    begin
      en___X_x_r3_raddr_ID = 0;         // __X_x_r3_raddr
      en_pca_ohe_sel_ID = 0;            // pca
      en_agu_ohe_sel_ID = 0;            // agu
      en_controller_bin_sel_ID = 0;     // controller
      en_reg_PC_EX_ohe_sel_ID = 0;      // reg_PC_EX
      en_mem_DMb_bin_sel_ID = 0;        // mem_DMb
      en_mux_dm_addr_ohe_sel_ID = 0;    // mux_dm_addr
      en_mux_pcaA_ohe_sel_ID = 0;       // mux_pcaA
      en_mux_pcaB_bin_sel_ID = 0;       // mux_pcaB
      en_mux_jmp_tgt_ID_ohe_sel_ID = 0; // mux_jmp_tgt_ID
      en_mux_aguB_bin_sel_ID = 0;       // mux_aguB
      en_mux___pidTGT_w_ohe_sel_ID = 0; // mux___pidTGT_w
    end

    predec_ID_enabling[0] = en_pca_ohe_sel_ID;
    predec_ID_enabling[1] = en_agu_ohe_sel_ID;
    predec_ID_enabling[3:2] = en_controller_bin_sel_ID;
    predec_ID_enabling[4] = en_reg_PC_EX_ohe_sel_ID;
    predec_ID_enabling[7:5] = en_mem_DMb_bin_sel_ID;
    predec_ID_enabling[8] = en_mux_dm_addr_ohe_sel_ID;
    predec_ID_enabling[9] = en_mux_pcaA_ohe_sel_ID;
    predec_ID_enabling[11:10] = en_mux_pcaB_bin_sel_ID;
    predec_ID_enabling[12] = en_mux_jmp_tgt_ID_ohe_sel_ID;
    predec_ID_enabling[14:13] = en_mux_aguB_bin_sel_ID;
    predec_ID_enabling[15] = en_mux___pidTGT_w_ohe_sel_ID;
    predec_ID_enabling[23:16] = en_hazards_decode_ID;
  end

  always @ (*)
  begin : decode_EX
    reg [3:0] en_alu_bin_sel_EX;
    reg [2:0] en_cmp_bin_sel_EX;
    reg en_divR_divs_divA_divB_div_EX;
    reg en_divR_divu_divA_divB_div_EX;
    reg en_divR_rems_divA_divB_div_EX;
    reg en_divR_remu_divA_divB_div_EX;
    reg [2:0] en_lx_bin_sel_EX;
    reg en_mpy_ohe_sel_EX;
    reg en_cnn_ohe_sel_EX;
    reg en_controller_ohe_sel_EX;
    reg [1:0] en_reg_X_bin_sel_EX;
    reg [2:0] en_mem_DMb_bin_sel_EX;
    reg en_mux_dmb_wr_ohe_sel_EX;
    reg [2:0] en_mux_x_w1_bin_sel_EX;
    reg en_mux_x_w1_dead_ohe_sel_EX;
    reg en_mux_aluA_ohe_sel_EX;
    reg [1:0] en_mux_aluB_bin_sel_EX;
    reg [1:0] en_mux_mpyM_bin_sel_EX;
    reg en_mux_ocd_swbreak_ohe_sel_EX;
    reg en_mux___X_x_w1_wad_ohe_sel_EX;
    reg en_hazards_decode_EX;


    en___X_x_r1_raddr_EX = 0;
    __X_x_r1_raddr_EX = 0;
    en___X_x_r2_raddr_EX = 0;
    __X_x_r2_raddr_EX = 0;
    en___X_x_r3_raddr_EX = 0;
    __X_x_r3_raddr_EX = 0;
    en___X_x_w2_waddr_EX = 0;
    __X_x_w2_waddr_EX = 0;

    en_alu_bin_sel_EX = 0;
    en_cmp_bin_sel_EX = 0;
    en_divR_divs_divA_divB_div_EX = 0;
    en_divR_divu_divA_divB_div_EX = 0;
    en_divR_rems_divA_divB_div_EX = 0;
    en_divR_remu_divA_divB_div_EX = 0;
    en_lx_bin_sel_EX = 0;
    en_mpy_ohe_sel_EX = 0;
    en_cnn_ohe_sel_EX = 0;
    en_controller_ohe_sel_EX = 0;
    en_reg_X_bin_sel_EX = 0;
    en_mem_DMb_bin_sel_EX = 0;
    en_mux_dmb_wr_ohe_sel_EX = 0;
    en_mux_x_w1_bin_sel_EX = 0;
    en_mux_x_w1_dead_ohe_sel_EX = 0;
    en_mux_aluA_ohe_sel_EX = 0;
    en_mux_aluB_bin_sel_EX = 0;
    en_mux_mpyM_bin_sel_EX = 0;
    en_mux_ocd_swbreak_ohe_sel_EX = 0;
    en_mux___X_x_w1_wad_ohe_sel_EX = 0;
    en_hazards_decode_EX = 0;

    if (trn_EX_valid)
    begin
      if (
           ( reg_IR_ID[31:25] == 7'b0000000 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b10011)                                                      // 0000000xxxxxxxxxxxxxxxxxx0x10011
        || ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[13] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b10011)                              // 000000xxxxxxxxxxxx1xxxxxx0x10011
        || ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[12] == 1'b0 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b10011)                              // 000000xxxxxxxxxxxxx0xxxxx0x10011
        || ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[6:0] == 7'b0110011)                                                                             // 000000xxxxxxxxxxxxxxxxxxx0110011
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b10011) // 0x00000xxxxxxxxxx000xxxxx0x10011
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:12] == 3'b101 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b10011) // 0x00000xxxxxxxxxx101xxxxx0x10011
        || ( reg_IR_ID[31:25] == 7'b1100000 && reg_IR_ID[14:12] == 3'b001 && reg_IR_ID[6:0] == 7'b0110011)                                              // 1100000xxxxxxxxxx001xxxxx0110011
        || ( reg_IR_ID[14] == 1'b1 && reg_IR_ID[6:0] == 7'b1100011)                                                                                     // xxxxxxxxxxxxxxxxx1xxxxxxx1100011
        || ( reg_IR_ID[13] == 1'b0 && reg_IR_ID[6:0] == 7'b1100011)                                                                                     // xxxxxxxxxxxxxxxxxx0xxxxxx1100011
        || ( reg_IR_ID[13] == 1'b1 && reg_IR_ID[6:0] == 7'b0010011)                                                                                     // xxxxxxxxxxxxxxxxxx1xxxxxx0010011
        || ( reg_IR_ID[12] == 1'b0 && reg_IR_ID[6:0] == 7'b0010011)                                                                                     // xxxxxxxxxxxxxxxxxxx0xxxxx0010011
         )
      begin
        en___X_x_r1_raddr_EX = 1'b1;
        __X_x_r1_raddr_EX = reg_IR_ID[19:15]; // __X_x_r1_raddr_cp___CTt5u_cstP15_EX_EX [alu.n:69][alu.n:131][alu.n:167][mpy.n:61][div.n:58][ctrl.n:94][cnn.n:26](regX.n:75)(regX.n:121)
      end
      if (
           ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[6:0] == 7'b0110011)                                                                               // 000000xxxxxxxxxxxxxxxxxxx0110011
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[6:5] == 2'b01 && reg_IR_ID[3:0] == 4'b0011) // 0x00000xxxxxxxxxx000xxxxx01x0011
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:12] == 3'b101 && reg_IR_ID[6:0] == 7'b0110011)                         // 0x00000xxxxxxxxxx101xxxxx0110011
        || ( reg_IR_ID[31:25] == 7'b1100000 && reg_IR_ID[14:12] == 3'b001 && reg_IR_ID[6:5] == 2'b01 && reg_IR_ID[3:0] == 4'b0011)                        // 1100000xxxxxxxxxx001xxxxx01x0011
        || ( reg_IR_ID[14:13] == 2'b00 && reg_IR_ID[5:0] == 6'b100011)                                                                                    // xxxxxxxxxxxxxxxxx00xxxxxxx100011
        || ( reg_IR_ID[14] == 1'b0 && reg_IR_ID[12] == 1'b0 && reg_IR_ID[6:0] == 7'b0100011)                                                              // xxxxxxxxxxxxxxxxx0x0xxxxx0100011
        || ( reg_IR_ID[14] == 1'b1 && reg_IR_ID[6:0] == 7'b1100011)                                                                                       // xxxxxxxxxxxxxxxxx1xxxxxxx1100011
        || ( reg_IR_ID[13] == 1'b0 && reg_IR_ID[6:0] == 7'b1100011)                                                                                       // xxxxxxxxxxxxxxxxxx0xxxxxx1100011
         )
      begin
        en___X_x_r2_raddr_EX = 1'b1;
        __X_x_r2_raddr_EX = reg_IR_ID[24:20]; // __X_x_r2_raddr_cp___CTt5u_cstP20_EX_EX [alu.n:70][mpy.n:62][div.n:59][ldst.n:99][ldst.n:100][ldst.n:101][ctrl.n:95][cnn.n:27](regX.n:82)(regX.n:114)
      end
      if (
           ( reg_IR_ID[31:25] == 7'b1100000 && reg_IR_ID[14:12] == 3'b001 && reg_IR_ID[6:0] == 7'b0110011) // 1100000xxxxxxxxxx001xxxxx0110011
         )
      begin
        en___X_x_r3_raddr_EX = 1'b1;
        __X_x_r3_raddr_EX = reg_IR_ID[11:7]; // __X_x_r3_raddr_cp___CTt5u_cstP7_EX_EX [cnn.n:28](regX.n:107)
        en_cnn_ohe_sel_EX = 1'b1;            // cnn_R_mac_xuC_xuA_xuB_cnn_EX [cnn.n:31]
      end
      if (
           ( reg_IR_ID[31:25] == 7'b1100000 && reg_IR_ID[14:11] == 4'b0011 && reg_IR_ID[6:0] == 7'b0110011)                         // 1100000xxxxxxxxxx0011xxxx0110011
        || ( reg_IR_ID[31:25] == 7'b1100000 && reg_IR_ID[14:12] == 3'b001 && reg_IR_ID[10] == 1'b1 && reg_IR_ID[6:0] == 7'b0110011) // 1100000xxxxxxxxxx001x1xxx0110011
        || ( reg_IR_ID[31:25] == 7'b1100000 && reg_IR_ID[14:12] == 3'b001 && reg_IR_ID[9] == 1'b1 && reg_IR_ID[6:0] == 7'b0110011)  // 1100000xxxxxxxxxx001xx1xx0110011
        || ( reg_IR_ID[31:25] == 7'b1100000 && reg_IR_ID[14:12] == 3'b001 && reg_IR_ID[8] == 1'b1 && reg_IR_ID[6:0] == 7'b0110011)  // 1100000xxxxxxxxxx001xxx1x0110011
        || ( reg_IR_ID[31:25] == 7'b1100000 && reg_IR_ID[14:12] == 3'b001 && reg_IR_ID[7:0] == 8'b10110011)                         // 1100000xxxxxxxxxx001xxxx10110011
         )
      begin
        en___X_x_w2_waddr_EX = 1'b1;
        __X_x_w2_waddr_EX = reg_IR_ID[11:7]; // __X_x_w2_waddr_cp___CTt5u_cstP7_EX_EX [cnn.n:35](regX.n:107)
        en_reg_X_bin_sel_EX = 2'b10;         // X_wr_x_w2___X_x_w2_wad_EX [cnn.n:35](regX.n:107)
      end
      if (
           ( reg_IR_ID[31:25] == 7'b0000000 && reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b10011) // 0000000xxxxxxxxxx000xxxxx0x10011
        || ( reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[6:3] == 4'b0010 && reg_IR_ID[1:0] == 2'b11)                                 // xxxxxxxxxxxxxxxxx000xxxxx0010x11
        || ( reg_IR_ID[6:0] == 7'b0010111)                                                                                       // xxxxxxxxxxxxxxxxxxxxxxxxx0010111
         )
      begin
        en_alu_bin_sel_EX = 4'b0001; // aluR_add_aluA_aluB_alu_EX [alu.n:74][alu.n:136][alu.n:213]
      end
      if (
           ( reg_IR_ID[31:25] == 7'b0000000 && reg_IR_ID[14:12] == 3'b111 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b10011) // 0000000xxxxxxxxxx111xxxxx0x10011
        || ( reg_IR_ID[14:12] == 3'b111 && reg_IR_ID[6:0] == 7'b0010011)                                                         // xxxxxxxxxxxxxxxxx111xxxxx0010011
         )
      begin
        en_alu_bin_sel_EX = 4'b0010; // aluR_band_aluA_aluB_alu_EX [alu.n:80][alu.n:140]
      end
      if (
           ( reg_IR_ID[31:25] == 7'b0000000 && reg_IR_ID[14:12] == 3'b110 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b10011) // 0000000xxxxxxxxxx110xxxxx0x10011
        || ( reg_IR_ID[14:12] == 3'b110 && reg_IR_ID[6:0] == 7'b0010011)                                                         // xxxxxxxxxxxxxxxxx110xxxxx0010011
         )
      begin
        en_alu_bin_sel_EX = 4'b0011; // aluR_bor_aluA_aluB_alu_EX [alu.n:79][alu.n:141]
      end
      if (
           ( reg_IR_ID[31:25] == 7'b0000000 && reg_IR_ID[14:12] == 3'b100 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b10011) // 0000000xxxxxxxxxx100xxxxx0x10011
        || ( reg_IR_ID[14:12] == 3'b100 && reg_IR_ID[6:0] == 7'b0010011)                                                         // xxxxxxxxxxxxxxxxx100xxxxx0010011
         )
      begin
        en_alu_bin_sel_EX = 4'b0100; // aluR_bxor_aluA_aluB_alu_EX [alu.n:78][alu.n:139]
      end
      if (
           ( reg_IR_ID[31:25] == 7'b0000000 && reg_IR_ID[14:12] == 3'b001 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b10011) // 0000000xxxxxxxxxx001xxxxx0x10011
         )
      begin
        en_alu_bin_sel_EX = 4'b0101; // aluR_sll_aluA_aluB_alu_EX [alu.n:81][alu.n:172]
      end
      if (
           ( reg_IR_ID[31:25] == 7'b0000000 && reg_IR_ID[14:12] == 3'b010 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b10011) // 0000000xxxxxxxxxx010xxxxx0x10011
        || ( reg_IR_ID[14:12] == 3'b010 && reg_IR_ID[6:0] == 7'b0010011)                                                         // xxxxxxxxxxxxxxxxx010xxxxx0010011
         )
      begin
        en_alu_bin_sel_EX = 4'b0110; // aluR_slt_aluA_aluB_alu_EX [alu.n:76][alu.n:137]
      end
      if (
           ( reg_IR_ID[31:25] == 7'b0000000 && reg_IR_ID[14:12] == 3'b011 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b10011) // 0000000xxxxxxxxxx011xxxxx0x10011
        || ( reg_IR_ID[14:12] == 3'b011 && reg_IR_ID[6:0] == 7'b0010011)                                                         // xxxxxxxxxxxxxxxxx011xxxxx0010011
         )
      begin
        en_alu_bin_sel_EX = 4'b0111; // aluR_sltu_aluA_aluB_alu_EX [alu.n:77][alu.n:138]
      end
      if (
           ( reg_IR_ID[31:25] == 7'b0100000 && reg_IR_ID[14:12] == 3'b101 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b10011) // 0100000xxxxxxxxxx101xxxxx0x10011
         )
      begin
        en_alu_bin_sel_EX = 4'b1000; // aluR_sra_aluA_aluB_alu_EX [alu.n:83][alu.n:174]
      end
      if (
           ( reg_IR_ID[31:25] == 7'b0000000 && reg_IR_ID[14:12] == 3'b101 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b10011) // 0000000xxxxxxxxxx101xxxxx0x10011
         )
      begin
        en_alu_bin_sel_EX = 4'b1001; // aluR_srl_aluA_aluB_alu_EX [alu.n:82][alu.n:173]
      end
      if (
           ( reg_IR_ID[31:25] == 7'b0100000 && reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[6:0] == 7'b0110011) // 0100000xxxxxxxxxx000xxxxx0110011
         )
      begin
        en_alu_bin_sel_EX = 4'b1010; // aluR_sub_aluA_aluB_alu_EX [alu.n:75]
      end
      if (
           ( reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[6:0] == 7'b1100011) // xxxxxxxxxxxxxxxxx000xxxxx1100011
         )
      begin
        en_cmp_bin_sel_EX = 3'b001; // cmpF_eq_cmpA_cmpB_cmp_EX [ctrl.n:99]
      end
      if (
           ( reg_IR_ID[14:12] == 3'b101 && reg_IR_ID[6:0] == 7'b1100011) // xxxxxxxxxxxxxxxxx101xxxxx1100011
         )
      begin
        en_cmp_bin_sel_EX = 3'b010; // cmpF_ge_cmpA_cmpB_cmp_EX [ctrl.n:103]
      end
      if (
           ( reg_IR_ID[14:12] == 3'b111 && reg_IR_ID[6:0] == 7'b1100011) // xxxxxxxxxxxxxxxxx111xxxxx1100011
         )
      begin
        en_cmp_bin_sel_EX = 3'b011; // cmpF_geu_cmpA_cmpB_cmp_EX [ctrl.n:104]
      end
      if (
           ( reg_IR_ID[14:12] == 3'b100 && reg_IR_ID[6:0] == 7'b1100011) // xxxxxxxxxxxxxxxxx100xxxxx1100011
         )
      begin
        en_cmp_bin_sel_EX = 3'b100; // cmpF_lt_cmpA_cmpB_cmp_EX [ctrl.n:101]
      end
      if (
           ( reg_IR_ID[14:12] == 3'b110 && reg_IR_ID[6:0] == 7'b1100011) // xxxxxxxxxxxxxxxxx110xxxxx1100011
         )
      begin
        en_cmp_bin_sel_EX = 3'b101; // cmpF_ltu_cmpA_cmpB_cmp_EX [ctrl.n:102]
      end
      if (
           ( reg_IR_ID[14:12] == 3'b001 && reg_IR_ID[6:0] == 7'b1100011) // xxxxxxxxxxxxxxxxx001xxxxx1100011
         )
      begin
        en_cmp_bin_sel_EX = 3'b110; // cmpF_ne_cmpA_cmpB_cmp_EX [ctrl.n:100]
      end
      if (
           ( reg_IR_ID[31:25] == 7'b0000001 && reg_IR_ID[14:12] == 3'b100 && reg_IR_ID[6:0] == 7'b0110011) // 0000001xxxxxxxxxx100xxxxx0110011
         )
      begin
        en_divR_divs_divA_divB_div_EX = 1'b1; // divR_divs_divA_divB_div_EX [div.n:66]
      end
      if (
           ( reg_IR_ID[31:25] == 7'b0000001 && reg_IR_ID[14:12] == 3'b101 && reg_IR_ID[6:0] == 7'b0110011) // 0000001xxxxxxxxxx101xxxxx0110011
         )
      begin
        en_divR_divu_divA_divB_div_EX = 1'b1; // divR_divu_divA_divB_div_EX [div.n:64]
      end
      if (
           ( reg_IR_ID[31:25] == 7'b0000001 && reg_IR_ID[14:12] == 3'b110 && reg_IR_ID[6:0] == 7'b0110011) // 0000001xxxxxxxxxx110xxxxx0110011
         )
      begin
        en_divR_rems_divA_divB_div_EX = 1'b1; // divR_rems_divA_divB_div_EX [div.n:67]
      end
      if (
           ( reg_IR_ID[31:25] == 7'b0000001 && reg_IR_ID[14:12] == 3'b111 && reg_IR_ID[6:0] == 7'b0110011) // 0000001xxxxxxxxxx111xxxxx0110011
         )
      begin
        en_divR_remu_divA_divB_div_EX = 1'b1; // divR_remu_divA_divB_div_EX [div.n:65]
      end
      if (
           ( reg_IR_ID[14:12] == 3'b010 && reg_IR_ID[6:0] == 7'b0000011) // xxxxxxxxxxxxxxxxx010xxxxx0000011
         )
      begin
        en_lx_bin_sel_EX = 3'b001;      // lxR_copy0_dmw_rd_lx_EX [ldst.n:72]
        en_mem_DMb_bin_sel_EX = 3'b101; // cp_extin_dmw_rd_ld_DMw_dm_addr_ID [ldst.n:64]
      end
      if (
           ( reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[6:0] == 7'b0000011) // xxxxxxxxxxxxxxxxx000xxxxx0000011
         )
      begin
        en_lx_bin_sel_EX = 3'b010; // lxR_sext_lxB_lx_EX [ldst.n:68]
      end
      if (
           ( reg_IR_ID[14:12] == 3'b001 && reg_IR_ID[6:0] == 7'b0000011) // xxxxxxxxxxxxxxxxx001xxxxx0000011
         )
      begin
        en_lx_bin_sel_EX = 3'b011; // lxR_sext_lxH_lx_EX [ldst.n:70]
      end
      if (
           ( reg_IR_ID[14:12] == 3'b100 && reg_IR_ID[6:0] == 7'b0000011) // xxxxxxxxxxxxxxxxx100xxxxx0000011
         )
      begin
        en_lx_bin_sel_EX = 3'b100; // lxR_zext_lxB_lx_EX [ldst.n:69]
      end
      if (
           ( reg_IR_ID[14:12] == 3'b101 && reg_IR_ID[6:0] == 7'b0000011) // xxxxxxxxxxxxxxxxx101xxxxx0000011
         )
      begin
        en_lx_bin_sel_EX = 3'b101; // lxR_zext_lxH_lx_EX [ldst.n:71]
      end
      if (
           ( reg_IR_ID[31:25] == 7'b0000001 && reg_IR_ID[14] == 1'b0 && reg_IR_ID[6:0] == 7'b0110011) // 0000001xxxxxxxxxx0xxxxxxx0110011
         )
      begin
        en_mpy_ohe_sel_EX = 1'b1; // vd_mul_hw_mpyA_mpyB_mpyM_mpyL_mpyH_mpy_EX [mpy.n:66][mpy.n:67][mpy.n:68][mpy.n:69]
      end
      if (
           ( reg_IR_ID[14] == 1'b1 && reg_IR_ID[6:0] == 7'b1100011) // xxxxxxxxxxxxxxxxx1xxxxxxx1100011
        || ( reg_IR_ID[13] == 1'b0 && reg_IR_ID[6:0] == 7'b1100011) // xxxxxxxxxxxxxxxxxx0xxxxxx1100011
         )
      begin
        en_controller_ohe_sel_EX = 1'b1; // vd_br_cnd_of13_cd_EX [ctrl.n:106]
      end
      if (
           ( reg_IR_ID[31:25] == 7'b0000000 && reg_IR_ID[11] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                                                      // 0000000xxxxxxxxxxxxx1xxxx0x10x11
        || ( reg_IR_ID[31:25] == 7'b0000000 && reg_IR_ID[10] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                                                      // 0000000xxxxxxxxxxxxxx1xxx0x10x11
        || ( reg_IR_ID[31:25] == 7'b0000000 && reg_IR_ID[9] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                                                       // 0000000xxxxxxxxxxxxxxx1xx0x10x11
        || ( reg_IR_ID[31:25] == 7'b0000000 && reg_IR_ID[8] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                                                       // 0000000xxxxxxxxxxxxxxxx1x0x10x11
        || ( reg_IR_ID[31:25] == 7'b0000000 && reg_IR_ID[7:6] == 2'b10 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                                                                            // 0000000xxxxxxxxxxxxxxxxx10x10x11
        || ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[14:13] == 2'b01 && reg_IR_ID[11] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                          // 000000xxxxxxxxxxx01x1xxxx0x10x11
        || ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[14:13] == 2'b01 && reg_IR_ID[10] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                          // 000000xxxxxxxxxxx01xx1xxx0x10x11
        || ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[14:13] == 2'b01 && reg_IR_ID[9] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                           // 000000xxxxxxxxxxx01xxx1xx0x10x11
        || ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[14:13] == 2'b01 && reg_IR_ID[8] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                           // 000000xxxxxxxxxxx01xxxx1x0x10x11
        || ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[14:13] == 2'b01 && reg_IR_ID[7:6] == 2'b10 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                                                // 000000xxxxxxxxxxx01xxxxx10x10x11
        || ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[14] == 1'b0 && reg_IR_ID[11] == 1'b1 && reg_IR_ID[6:3] == 4'b0110 && reg_IR_ID[1:0] == 2'b11)                                                    // 000000xxxxxxxxxxx0xx1xxxx0110x11
        || ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[14] == 1'b0 && reg_IR_ID[10] == 1'b1 && reg_IR_ID[6:3] == 4'b0110 && reg_IR_ID[1:0] == 2'b11)                                                    // 000000xxxxxxxxxxx0xxx1xxx0110x11
        || ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[14] == 1'b0 && reg_IR_ID[9] == 1'b1 && reg_IR_ID[6:3] == 4'b0110 && reg_IR_ID[1:0] == 2'b11)                                                     // 000000xxxxxxxxxxx0xxxx1xx0110x11
        || ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[14] == 1'b0 && reg_IR_ID[8] == 1'b1 && reg_IR_ID[6:3] == 4'b0110 && reg_IR_ID[1:0] == 2'b11)                                                     // 000000xxxxxxxxxxx0xxxxx1x0110x11
        || ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[14] == 1'b0 && reg_IR_ID[7:3] == 5'b10110 && reg_IR_ID[1:0] == 2'b11)                                                                            // 000000xxxxxxxxxxx0xxxxxx10110x11
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:11] == 4'b0001 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                         // 0x00000xxxxxxxxxx0001xxxx0x10x11
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[10] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11) // 0x00000xxxxxxxxxx000x1xxx0x10x11
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[9] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)  // 0x00000xxxxxxxxxx000xx1xx0x10x11
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[8] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)  // 0x00000xxxxxxxxxx000xxx1x0x10x11
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[7:6] == 2'b10 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                       // 0x00000xxxxxxxxxx000xxxx10x10x11
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:11] == 4'b1011 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                         // 0x00000xxxxxxxxxx1011xxxx0x10x11
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:12] == 3'b101 && reg_IR_ID[10] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11) // 0x00000xxxxxxxxxx101x1xxx0x10x11
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:12] == 3'b101 && reg_IR_ID[9] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)  // 0x00000xxxxxxxxxx101xx1xx0x10x11
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:12] == 3'b101 && reg_IR_ID[8] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)  // 0x00000xxxxxxxxxx101xxx1x0x10x11
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:12] == 3'b101 && reg_IR_ID[7:6] == 2'b10 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                       // 0x00000xxxxxxxxxx101xxxx10x10x11
        || ( reg_IR_ID[14:11] == 4'b0001 && reg_IR_ID[6:4] == 3'b110 && reg_IR_ID[2:0] == 3'b111)                                                                                                        // xxxxxxxxxxxxxxxxx0001xxxx110x111
        || ( reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[10] == 1'b1 && reg_IR_ID[6:4] == 3'b110 && reg_IR_ID[2:0] == 3'b111)                                                                                // xxxxxxxxxxxxxxxxx000x1xxx110x111
        || ( reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[9] == 1'b1 && reg_IR_ID[6:4] == 3'b110 && reg_IR_ID[2:0] == 3'b111)                                                                                 // xxxxxxxxxxxxxxxxx000xx1xx110x111
        || ( reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[8] == 1'b1 && reg_IR_ID[6:4] == 3'b110 && reg_IR_ID[2:0] == 3'b111)                                                                                 // xxxxxxxxxxxxxxxxx000xxx1x110x111
        || ( reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[7:4] == 4'b1110 && reg_IR_ID[2:0] == 3'b111)                                                                                                        // xxxxxxxxxxxxxxxxx000xxxx1110x111
        || ( reg_IR_ID[14] == 1'b0 && reg_IR_ID[12:11] == 2'b01 && reg_IR_ID[6:5] == 2'b00 && reg_IR_ID[3:0] == 4'b0011)                                                                                 // xxxxxxxxxxxxxxxxx0x01xxxx00x0011
        || ( reg_IR_ID[14] == 1'b0 && reg_IR_ID[12] == 1'b0 && reg_IR_ID[10] == 1'b1 && reg_IR_ID[6:5] == 2'b00 && reg_IR_ID[3:0] == 4'b0011)                                                            // xxxxxxxxxxxxxxxxx0x0x1xxx00x0011
        || ( reg_IR_ID[14] == 1'b0 && reg_IR_ID[12] == 1'b0 && reg_IR_ID[9] == 1'b1 && reg_IR_ID[6:5] == 2'b00 && reg_IR_ID[3:0] == 4'b0011)                                                             // xxxxxxxxxxxxxxxxx0x0xx1xx00x0011
        || ( reg_IR_ID[14] == 1'b0 && reg_IR_ID[12] == 1'b0 && reg_IR_ID[8] == 1'b1 && reg_IR_ID[6:5] == 2'b00 && reg_IR_ID[3:0] == 4'b0011)                                                             // xxxxxxxxxxxxxxxxx0x0xxx1x00x0011
        || ( reg_IR_ID[14] == 1'b0 && reg_IR_ID[12] == 1'b0 && reg_IR_ID[7:5] == 3'b100 && reg_IR_ID[3:0] == 4'b0011)                                                                                    // xxxxxxxxxxxxxxxxx0x0xxxx100x0011
        || ( reg_IR_ID[13] == 1'b0 && reg_IR_ID[11] == 1'b1 && reg_IR_ID[6:0] == 7'b0000011)                                                                                                             // xxxxxxxxxxxxxxxxxx0x1xxxx0000011
        || ( reg_IR_ID[13] == 1'b0 && reg_IR_ID[10] == 1'b1 && reg_IR_ID[6:0] == 7'b0000011)                                                                                                             // xxxxxxxxxxxxxxxxxx0xx1xxx0000011
        || ( reg_IR_ID[13] == 1'b0 && reg_IR_ID[9] == 1'b1 && reg_IR_ID[6:0] == 7'b0000011)                                                                                                              // xxxxxxxxxxxxxxxxxx0xxx1xx0000011
        || ( reg_IR_ID[13] == 1'b0 && reg_IR_ID[8] == 1'b1 && reg_IR_ID[6:0] == 7'b0000011)                                                                                                              // xxxxxxxxxxxxxxxxxx0xxxx1x0000011
        || ( reg_IR_ID[13] == 1'b0 && reg_IR_ID[7:0] == 8'b10000011)                                                                                                                                     // xxxxxxxxxxxxxxxxxx0xxxxx10000011
        || ( reg_IR_ID[13] == 1'b1 && reg_IR_ID[11] == 1'b1 && reg_IR_ID[6:3] == 4'b0010 && reg_IR_ID[1:0] == 2'b11)                                                                                     // xxxxxxxxxxxxxxxxxx1x1xxxx0010x11
        || ( reg_IR_ID[13] == 1'b1 && reg_IR_ID[10] == 1'b1 && reg_IR_ID[6:3] == 4'b0010 && reg_IR_ID[1:0] == 2'b11)                                                                                     // xxxxxxxxxxxxxxxxxx1xx1xxx0010x11
        || ( reg_IR_ID[13] == 1'b1 && reg_IR_ID[9] == 1'b1 && reg_IR_ID[6:3] == 4'b0010 && reg_IR_ID[1:0] == 2'b11)                                                                                      // xxxxxxxxxxxxxxxxxx1xxx1xx0010x11
        || ( reg_IR_ID[13] == 1'b1 && reg_IR_ID[8] == 1'b1 && reg_IR_ID[6:3] == 4'b0010 && reg_IR_ID[1:0] == 2'b11)                                                                                      // xxxxxxxxxxxxxxxxxx1xxxx1x0010x11
        || ( reg_IR_ID[13] == 1'b1 && reg_IR_ID[7:3] == 5'b10010 && reg_IR_ID[1:0] == 2'b11)                                                                                                             // xxxxxxxxxxxxxxxxxx1xxxxx10010x11
        || ( reg_IR_ID[12:11] == 2'b01 && reg_IR_ID[6:3] == 4'b0010 && reg_IR_ID[1:0] == 2'b11)                                                                                                          // xxxxxxxxxxxxxxxxxxx01xxxx0010x11
        || ( reg_IR_ID[12] == 1'b0 && reg_IR_ID[10] == 1'b1 && reg_IR_ID[6:3] == 4'b0010 && reg_IR_ID[1:0] == 2'b11)                                                                                     // xxxxxxxxxxxxxxxxxxx0x1xxx0010x11
        || ( reg_IR_ID[12] == 1'b0 && reg_IR_ID[9] == 1'b1 && reg_IR_ID[6:3] == 4'b0010 && reg_IR_ID[1:0] == 2'b11)                                                                                      // xxxxxxxxxxxxxxxxxxx0xx1xx0010x11
        || ( reg_IR_ID[12] == 1'b0 && reg_IR_ID[8] == 1'b1 && reg_IR_ID[6:3] == 4'b0010 && reg_IR_ID[1:0] == 2'b11)                                                                                      // xxxxxxxxxxxxxxxxxxx0xxx1x0010x11
        || ( reg_IR_ID[12] == 1'b0 && reg_IR_ID[7:3] == 5'b10010 && reg_IR_ID[1:0] == 2'b11)                                                                                                             // xxxxxxxxxxxxxxxxxxx0xxxx10010x11
        || ( reg_IR_ID[11] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b10111)                                                                                                                // xxxxxxxxxxxxxxxxxxxx1xxxx0x10111
        || ( reg_IR_ID[11] == 1'b1 && reg_IR_ID[6:0] == 7'b1101111)                                                                                                                                      // xxxxxxxxxxxxxxxxxxxx1xxxx1101111
        || ( reg_IR_ID[10] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b10111)                                                                                                                // xxxxxxxxxxxxxxxxxxxxx1xxx0x10111
        || ( reg_IR_ID[10] == 1'b1 && reg_IR_ID[6:0] == 7'b1101111)                                                                                                                                      // xxxxxxxxxxxxxxxxxxxxx1xxx1101111
        || ( reg_IR_ID[9] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b10111)                                                                                                                 // xxxxxxxxxxxxxxxxxxxxxx1xx0x10111
        || ( reg_IR_ID[9] == 1'b1 && reg_IR_ID[6:0] == 7'b1101111)                                                                                                                                       // xxxxxxxxxxxxxxxxxxxxxx1xx1101111
        || ( reg_IR_ID[8] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b10111)                                                                                                                 // xxxxxxxxxxxxxxxxxxxxxxx1x0x10111
        || ( reg_IR_ID[8] == 1'b1 && reg_IR_ID[6:0] == 7'b1101111)                                                                                                                                       // xxxxxxxxxxxxxxxxxxxxxxx1x1101111
        || ( reg_IR_ID[7:6] == 2'b10 && reg_IR_ID[4:0] == 5'b10111)                                                                                                                                      // xxxxxxxxxxxxxxxxxxxxxxxx10x10111
        || ( reg_IR_ID[7:0] == 8'b11101111)                                                                                                                                                              // xxxxxxxxxxxxxxxxxxxxxxxx11101111
         )
      begin
        en_reg_X_bin_sel_EX = 2'b01;           // X_wr_x_w1___X_x_w1_wad_EX [regX.n:99]
        en_mux___X_x_w1_wad_ohe_sel_EX = 1'b1; // __X_x_w1_wad_copy0___CTt5u_cstP7_EX [regX.n:99]
      end
      if (
           ( reg_IR_ID[13:12] == 2'b00 && reg_IR_ID[6:0] == 7'b0000011) // xxxxxxxxxxxxxxxxxx00xxxxx0000011
         )
      begin
        en_mem_DMb_bin_sel_EX = 3'b001; // cp_extin_dmb_rd_ld_DMb_dm_addr_ID [ldst.n:62]
      end
      if (
           ( reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[6:0] == 7'b0100011) // xxxxxxxxxxxxxxxxx000xxxxx0100011
         )
      begin
        en_mem_DMb_bin_sel_EX = 3'b010;  // cp_extout_DMb_st_dmb_wr_dm_addr_ID [ldst.n:99]
        en_mux_dmb_wr_ohe_sel_EX = 1'b1; // dmb_wr_copy0_x_r2_EX [ldst.n:99](regX.n:82)
      end
      if (
           ( reg_IR_ID[13:12] == 2'b01 && reg_IR_ID[6:0] == 7'b0000011) // xxxxxxxxxxxxxxxxxx01xxxxx0000011
         )
      begin
        en_mem_DMb_bin_sel_EX = 3'b011; // cp_extin_dmh_rd_ld_DMh_dm_addr_ID [ldst.n:63]
      end
      if (
           ( reg_IR_ID[14:12] == 3'b001 && reg_IR_ID[6:0] == 7'b0100011) // xxxxxxxxxxxxxxxxx001xxxxx0100011
         )
      begin
        en_mem_DMb_bin_sel_EX = 3'b100; // cp_extout_DMh_st_dmh_wr_dm_addr_ID [ldst.n:100]
      end
      if (
           ( reg_IR_ID[14:12] == 3'b010 && reg_IR_ID[6:0] == 7'b0100011) // xxxxxxxxxxxxxxxxx010xxxxx0100011
         )
      begin
        en_mem_DMb_bin_sel_EX = 3'b110; // cp_extout_DMw_st_dmw_wr_dm_addr_ID [ldst.n:101]
      end
      if (
           ( reg_IR_ID[6:0] == 7'b0110111) // xxxxxxxxxxxxxxxxxxxxxxxxx0110111
         )
      begin
        en_mux_x_w1_bin_sel_EX = 3'b001; // luiU_copy0___CTt20s_rp12_cstP12_EX [alu.n:191]
      end
      if (
           ( reg_IR_ID[31:25] == 7'b0000001 && reg_IR_ID[14:13] == 2'b01 && reg_IR_ID[6:0] == 7'b0110011)                      // 0000001xxxxxxxxxx01xxxxxx0110011
        || ( reg_IR_ID[31:25] == 7'b0000001 && reg_IR_ID[14] == 1'b0 && reg_IR_ID[12] == 1'b1 && reg_IR_ID[6:0] == 7'b0110011) // 0000001xxxxxxxxxx0x1xxxxx0110011
         )
      begin
        en_mux_x_w1_bin_sel_EX = 3'b010; // mpyR_copy0_mpyH_EX [mpy.n:76]
      end
      if (
           ( reg_IR_ID[31:25] == 7'b0000001 && reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[6:0] == 7'b0110011) // 0000001xxxxxxxxxx000xxxxx0110011
         )
      begin
        en_mux_x_w1_bin_sel_EX = 3'b011; // mpyR_copy0_mpyL_EX [mpy.n:73]
      end
      if (
           ( reg_IR_ID[31:25] == 7'b0000000 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b10011)                                                      // 0000000xxxxxxxxxxxxxxxxxx0x10011
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b10011) // 0x00000xxxxxxxxxx000xxxxx0x10011
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:12] == 3'b101 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b10011) // 0x00000xxxxxxxxxx101xxxxx0x10011
        || ( reg_IR_ID[13] == 1'b1 && reg_IR_ID[6:3] == 4'b0010 && reg_IR_ID[1:0] == 2'b11)                                                             // xxxxxxxxxxxxxxxxxx1xxxxxx0010x11
        || ( reg_IR_ID[12] == 1'b0 && reg_IR_ID[6:3] == 4'b0010 && reg_IR_ID[1:0] == 2'b11)                                                             // xxxxxxxxxxxxxxxxxxx0xxxxx0010x11
        || ( reg_IR_ID[6:0] == 7'b0010111)                                                                                                              // xxxxxxxxxxxxxxxxxxxxxxxxx0010111
         )
      begin
        en_mux_x_w1_bin_sel_EX = 3'b100; // x_w1_copy0_aluR_EX [alu.n:86][alu.n:144][alu.n:177][alu.n:215](regX.n:96)
      end
      if (
           ( reg_IR_ID[14] == 1'b0 && reg_IR_ID[12] == 1'b0 && reg_IR_ID[6:0] == 7'b0000011) // xxxxxxxxxxxxxxxxx0x0xxxxx0000011
        || ( reg_IR_ID[13] == 1'b0 && reg_IR_ID[6:0] == 7'b0000011)                          // xxxxxxxxxxxxxxxxxx0xxxxxx0000011
         )
      begin
        en_mux_x_w1_bin_sel_EX = 3'b101; // x_w1_copy0_lxR_EX [ldst.n:75](regX.n:96)
      end
      if (
           ( reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[6:4] == 3'b110 && reg_IR_ID[2:0] == 3'b111) // xxxxxxxxxxxxxxxxx000xxxxx110x111
        || ( reg_IR_ID[6:0] == 7'b1101111)                                                       // xxxxxxxxxxxxxxxxxxxxxxxxx1101111
         )
      begin
        en_mux_x_w1_bin_sel_EX = 3'b110; // x_w1_copy0_pidTGT_EX [ctrl.n:157][ctrl.n:196](regX.n:96)
      end
      if (
           ( reg_IR_ID[31:25] == 7'b0000000 && reg_IR_ID[11:6] == 6'b000000 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                             // 0000000xxxxxxxxxxxxx000000x10x11
        || ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[14:13] == 2'b01 && reg_IR_ID[11:6] == 6'b000000 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11) // 000000xxxxxxxxxxx01x000000x10x11
        || ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[14] == 1'b0 && reg_IR_ID[11:3] == 9'b000000110 && reg_IR_ID[1:0] == 2'b11)                             // 000000xxxxxxxxxxx0xx000000110x11
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:6] == 9'b000000000 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)   // 0x00000xxxxxxxxxx000000000x10x11
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:6] == 9'b101000000 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)   // 0x00000xxxxxxxxxx101000000x10x11
        || ( reg_IR_ID[14:4] == 11'b00000000110 && reg_IR_ID[2:0] == 3'b111)                                                                                   // xxxxxxxxxxxxxxxxx00000000110x111
        || ( reg_IR_ID[14] == 1'b0 && reg_IR_ID[12:5] == 8'b00000000 && reg_IR_ID[3:0] == 4'b0011)                                                             // xxxxxxxxxxxxxxxxx0x00000000x0011
        || ( reg_IR_ID[13] == 1'b0 && reg_IR_ID[11:0] == 12'b000000000011)                                                                                     // xxxxxxxxxxxxxxxxxx0x000000000011
        || ( reg_IR_ID[13] == 1'b1 && reg_IR_ID[11:3] == 9'b000000010 && reg_IR_ID[1:0] == 2'b11)                                                              // xxxxxxxxxxxxxxxxxx1x000000010x11
        || ( reg_IR_ID[12:3] == 10'b0000000010 && reg_IR_ID[1:0] == 2'b11)                                                                                     // xxxxxxxxxxxxxxxxxxx0000000010x11
        || ( reg_IR_ID[11:6] == 6'b000000 && reg_IR_ID[4:0] == 5'b10111)                                                                                       // xxxxxxxxxxxxxxxxxxxx000000x10111
        || ( reg_IR_ID[11:0] == 12'b000001101111)                                                                                                              // xxxxxxxxxxxxxxxxxxxx000001101111
         )
      begin
        en_mux_x_w1_dead_ohe_sel_EX = 1'b1; // x_w1_dead_copy0_x_w1_EX [regX.n:98]
      end
      if (
           ( reg_IR_ID[31:25] == 7'b0000000 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b10011)                                                      // 0000000xxxxxxxxxxxxxxxxxx0x10011
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b10011) // 0x00000xxxxxxxxxx000xxxxx0x10011
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:12] == 3'b101 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b10011) // 0x00000xxxxxxxxxx101xxxxx0x10011
        || ( reg_IR_ID[13] == 1'b1 && reg_IR_ID[6:0] == 7'b0010011)                                                                                     // xxxxxxxxxxxxxxxxxx1xxxxxx0010011
        || ( reg_IR_ID[12] == 1'b0 && reg_IR_ID[6:0] == 7'b0010011)                                                                                     // xxxxxxxxxxxxxxxxxxx0xxxxx0010011
         )
      begin
        en_mux_aluA_ohe_sel_EX = 1'b1; // aluA_copy0_x_r1_EX [alu.n:69][alu.n:131][alu.n:167](regX.n:75)
      end
      if (
           ( reg_IR_ID[13] == 1'b1 && reg_IR_ID[6:0] == 7'b0010011) // xxxxxxxxxxxxxxxxxx1xxxxxx0010011
        || ( reg_IR_ID[12] == 1'b0 && reg_IR_ID[6:0] == 7'b0010011) // xxxxxxxxxxxxxxxxxxx0xxxxx0010011
         )
      begin
        en_mux_aluB_bin_sel_EX = 2'b01; // aluB_copy0___CTt12s_cstP20_EX [alu.n:132]
      end
      if (
           ( reg_IR_ID[6:0] == 7'b0010111) // xxxxxxxxxxxxxxxxxxxxxxxxx0010111
         )
      begin
        en_mux_aluB_bin_sel_EX = 2'b10; // aluB_copy0___CTt20s_rp12_cstP12_EX [alu.n:211]
      end
      if (
           ( reg_IR_ID[31:25] == 7'b0000000 && reg_IR_ID[13:12] == 2'b01 && reg_IR_ID[6:0] == 7'b0010011)                         // 0000000xxxxxxxxxxx01xxxxx0010011
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:12] == 3'b101 && reg_IR_ID[6:0] == 7'b0010011) // 0x00000xxxxxxxxxx101xxxxx0010011
         )
      begin
        en_mux_aluB_bin_sel_EX = 2'b11; // aluB_copy0___CTt5u_cstP20_EX [alu.n:168]
      end
      if (
           ( reg_IR_ID[31:25] == 7'b0000001 && reg_IR_ID[14:12] == 3'b010 && reg_IR_ID[6:0] == 7'b0110011) // 0000001xxxxxxxxxx010xxxxx0110011
         )
      begin
        en_mux_mpyM_bin_sel_EX = 2'b01; // mpyM_copy0___CTt2u_cstV2_EX [mpy.n:68]
      end
      if (
           ( reg_IR_ID[31:25] == 7'b0000001 && reg_IR_ID[14:13] == 2'b00 && reg_IR_ID[6:0] == 7'b0110011) // 0000001xxxxxxxxxx00xxxxxx0110011
         )
      begin
        en_mux_mpyM_bin_sel_EX = 2'b10; // mpyM_copy0___CTt2u_cstV3_EX [mpy.n:66][mpy.n:67]
      end
      if (
           ( reg_IR_ID[31:0] == 32'b00000000000100000010000001111011) // 00000000000100000010000001111011
         )
      begin
        en_mux_ocd_swbreak_ohe_sel_EX = 1'b1; // ocd_swbreak_copy0___CTt1u_cstV1_EX [ocd.n:111]
      end
      if (
           ( reg_IR_ID[31:25] == 7'b0000000 && reg_IR_ID[11] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                                                      // 0000000xxxxxxxxxxxxx1xxxx0x10x11
        || ( reg_IR_ID[31:25] == 7'b0000000 && reg_IR_ID[10] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                                                      // 0000000xxxxxxxxxxxxxx1xxx0x10x11
        || ( reg_IR_ID[31:25] == 7'b0000000 && reg_IR_ID[9] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                                                       // 0000000xxxxxxxxxxxxxxx1xx0x10x11
        || ( reg_IR_ID[31:25] == 7'b0000000 && reg_IR_ID[8] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                                                       // 0000000xxxxxxxxxxxxxxxx1x0x10x11
        || ( reg_IR_ID[31:25] == 7'b0000000 && reg_IR_ID[7:6] == 2'b10 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                                                                            // 0000000xxxxxxxxxxxxxxxxx10x10x11
        || ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[14:13] == 2'b01 && reg_IR_ID[11] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                          // 000000xxxxxxxxxxx01x1xxxx0x10x11
        || ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[14:13] == 2'b01 && reg_IR_ID[10] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                          // 000000xxxxxxxxxxx01xx1xxx0x10x11
        || ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[14:13] == 2'b01 && reg_IR_ID[9] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                           // 000000xxxxxxxxxxx01xxx1xx0x10x11
        || ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[14:13] == 2'b01 && reg_IR_ID[8] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                           // 000000xxxxxxxxxxx01xxxx1x0x10x11
        || ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[14:13] == 2'b01 && reg_IR_ID[7:6] == 2'b10 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                                                // 000000xxxxxxxxxxx01xxxxx10x10x11
        || ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[14] == 1'b0 && reg_IR_ID[11] == 1'b1 && reg_IR_ID[6:3] == 4'b0110 && reg_IR_ID[1:0] == 2'b11)                                                    // 000000xxxxxxxxxxx0xx1xxxx0110x11
        || ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[14] == 1'b0 && reg_IR_ID[10] == 1'b1 && reg_IR_ID[6:3] == 4'b0110 && reg_IR_ID[1:0] == 2'b11)                                                    // 000000xxxxxxxxxxx0xxx1xxx0110x11
        || ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[14] == 1'b0 && reg_IR_ID[9] == 1'b1 && reg_IR_ID[6:3] == 4'b0110 && reg_IR_ID[1:0] == 2'b11)                                                     // 000000xxxxxxxxxxx0xxxx1xx0110x11
        || ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[14] == 1'b0 && reg_IR_ID[8] == 1'b1 && reg_IR_ID[6:3] == 4'b0110 && reg_IR_ID[1:0] == 2'b11)                                                     // 000000xxxxxxxxxxx0xxxxx1x0110x11
        || ( reg_IR_ID[31:26] == 6'b000000 && reg_IR_ID[14] == 1'b0 && reg_IR_ID[7:3] == 5'b10110 && reg_IR_ID[1:0] == 2'b11)                                                                            // 000000xxxxxxxxxxx0xxxxxx10110x11
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:11] == 4'b0001 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                         // 0x00000xxxxxxxxxx0001xxxx0x10x11
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[10] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11) // 0x00000xxxxxxxxxx000x1xxx0x10x11
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[9] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)  // 0x00000xxxxxxxxxx000xx1xx0x10x11
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[8] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)  // 0x00000xxxxxxxxxx000xxx1x0x10x11
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[7:6] == 2'b10 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                       // 0x00000xxxxxxxxxx000xxxx10x10x11
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:11] == 4'b1011 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                         // 0x00000xxxxxxxxxx1011xxxx0x10x11
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:12] == 3'b101 && reg_IR_ID[10] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11) // 0x00000xxxxxxxxxx101x1xxx0x10x11
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:12] == 3'b101 && reg_IR_ID[9] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)  // 0x00000xxxxxxxxxx101xx1xx0x10x11
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:12] == 3'b101 && reg_IR_ID[8] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)  // 0x00000xxxxxxxxxx101xxx1x0x10x11
        || ( reg_IR_ID[31] == 1'b0 && reg_IR_ID[29:25] == 5'b00000 && reg_IR_ID[14:12] == 3'b101 && reg_IR_ID[7:6] == 2'b10 && reg_IR_ID[4:3] == 2'b10 && reg_IR_ID[1:0] == 2'b11)                       // 0x00000xxxxxxxxxx101xxxx10x10x11
        || ( reg_IR_ID[31:25] == 7'b1100000 && reg_IR_ID[14:11] == 4'b0011 && reg_IR_ID[6:3] == 4'b0110 && reg_IR_ID[1:0] == 2'b11)                                                                      // 1100000xxxxxxxxxx0011xxxx0110x11
        || ( reg_IR_ID[31:25] == 7'b1100000 && reg_IR_ID[14:12] == 3'b001 && reg_IR_ID[10] == 1'b1 && reg_IR_ID[6:3] == 4'b0110 && reg_IR_ID[1:0] == 2'b11)                                              // 1100000xxxxxxxxxx001x1xxx0110x11
        || ( reg_IR_ID[31:25] == 7'b1100000 && reg_IR_ID[14:12] == 3'b001 && reg_IR_ID[9] == 1'b1 && reg_IR_ID[6:3] == 4'b0110 && reg_IR_ID[1:0] == 2'b11)                                               // 1100000xxxxxxxxxx001xx1xx0110x11
        || ( reg_IR_ID[31:25] == 7'b1100000 && reg_IR_ID[14:12] == 3'b001 && reg_IR_ID[8] == 1'b1 && reg_IR_ID[6:3] == 4'b0110 && reg_IR_ID[1:0] == 2'b11)                                               // 1100000xxxxxxxxxx001xxx1x0110x11
        || ( reg_IR_ID[31:25] == 7'b1100000 && reg_IR_ID[14:12] == 3'b001 && reg_IR_ID[7:3] == 5'b10110 && reg_IR_ID[1:0] == 2'b11)                                                                      // 1100000xxxxxxxxxx001xxxx10110x11
        || ( reg_IR_ID[14:11] == 4'b0001 && reg_IR_ID[6:4] == 3'b110 && reg_IR_ID[2:0] == 3'b111)                                                                                                        // xxxxxxxxxxxxxxxxx0001xxxx110x111
        || ( reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[10] == 1'b1 && reg_IR_ID[6:4] == 3'b110 && reg_IR_ID[2:0] == 3'b111)                                                                                // xxxxxxxxxxxxxxxxx000x1xxx110x111
        || ( reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[9] == 1'b1 && reg_IR_ID[6:4] == 3'b110 && reg_IR_ID[2:0] == 3'b111)                                                                                 // xxxxxxxxxxxxxxxxx000xx1xx110x111
        || ( reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[8] == 1'b1 && reg_IR_ID[6:4] == 3'b110 && reg_IR_ID[2:0] == 3'b111)                                                                                 // xxxxxxxxxxxxxxxxx000xxx1x110x111
        || ( reg_IR_ID[14:12] == 3'b000 && reg_IR_ID[7:4] == 4'b1110 && reg_IR_ID[2:0] == 3'b111)                                                                                                        // xxxxxxxxxxxxxxxxx000xxxx1110x111
        || ( reg_IR_ID[14] == 1'b0 && reg_IR_ID[12:11] == 2'b01 && reg_IR_ID[6:5] == 2'b00 && reg_IR_ID[3:0] == 4'b0011)                                                                                 // xxxxxxxxxxxxxxxxx0x01xxxx00x0011
        || ( reg_IR_ID[14] == 1'b0 && reg_IR_ID[12] == 1'b0 && reg_IR_ID[10] == 1'b1 && reg_IR_ID[6:5] == 2'b00 && reg_IR_ID[3:0] == 4'b0011)                                                            // xxxxxxxxxxxxxxxxx0x0x1xxx00x0011
        || ( reg_IR_ID[14] == 1'b0 && reg_IR_ID[12] == 1'b0 && reg_IR_ID[9] == 1'b1 && reg_IR_ID[6:5] == 2'b00 && reg_IR_ID[3:0] == 4'b0011)                                                             // xxxxxxxxxxxxxxxxx0x0xx1xx00x0011
        || ( reg_IR_ID[14] == 1'b0 && reg_IR_ID[12] == 1'b0 && reg_IR_ID[8] == 1'b1 && reg_IR_ID[6:5] == 2'b00 && reg_IR_ID[3:0] == 4'b0011)                                                             // xxxxxxxxxxxxxxxxx0x0xxx1x00x0011
        || ( reg_IR_ID[14] == 1'b0 && reg_IR_ID[12] == 1'b0 && reg_IR_ID[7:5] == 3'b100 && reg_IR_ID[3:0] == 4'b0011)                                                                                    // xxxxxxxxxxxxxxxxx0x0xxxx100x0011
        || ( reg_IR_ID[13] == 1'b0 && reg_IR_ID[11] == 1'b1 && reg_IR_ID[6:0] == 7'b0000011)                                                                                                             // xxxxxxxxxxxxxxxxxx0x1xxxx0000011
        || ( reg_IR_ID[13] == 1'b0 && reg_IR_ID[10] == 1'b1 && reg_IR_ID[6:0] == 7'b0000011)                                                                                                             // xxxxxxxxxxxxxxxxxx0xx1xxx0000011
        || ( reg_IR_ID[13] == 1'b0 && reg_IR_ID[9] == 1'b1 && reg_IR_ID[6:0] == 7'b0000011)                                                                                                              // xxxxxxxxxxxxxxxxxx0xxx1xx0000011
        || ( reg_IR_ID[13] == 1'b0 && reg_IR_ID[8] == 1'b1 && reg_IR_ID[6:0] == 7'b0000011)                                                                                                              // xxxxxxxxxxxxxxxxxx0xxxx1x0000011
        || ( reg_IR_ID[13] == 1'b0 && reg_IR_ID[7:0] == 8'b10000011)                                                                                                                                     // xxxxxxxxxxxxxxxxxx0xxxxx10000011
        || ( reg_IR_ID[13] == 1'b1 && reg_IR_ID[11] == 1'b1 && reg_IR_ID[6:3] == 4'b0010 && reg_IR_ID[1:0] == 2'b11)                                                                                     // xxxxxxxxxxxxxxxxxx1x1xxxx0010x11
        || ( reg_IR_ID[13] == 1'b1 && reg_IR_ID[10] == 1'b1 && reg_IR_ID[6:3] == 4'b0010 && reg_IR_ID[1:0] == 2'b11)                                                                                     // xxxxxxxxxxxxxxxxxx1xx1xxx0010x11
        || ( reg_IR_ID[13] == 1'b1 && reg_IR_ID[9] == 1'b1 && reg_IR_ID[6:3] == 4'b0010 && reg_IR_ID[1:0] == 2'b11)                                                                                      // xxxxxxxxxxxxxxxxxx1xxx1xx0010x11
        || ( reg_IR_ID[13] == 1'b1 && reg_IR_ID[8] == 1'b1 && reg_IR_ID[6:3] == 4'b0010 && reg_IR_ID[1:0] == 2'b11)                                                                                      // xxxxxxxxxxxxxxxxxx1xxxx1x0010x11
        || ( reg_IR_ID[13] == 1'b1 && reg_IR_ID[7:3] == 5'b10010 && reg_IR_ID[1:0] == 2'b11)                                                                                                             // xxxxxxxxxxxxxxxxxx1xxxxx10010x11
        || ( reg_IR_ID[12:11] == 2'b01 && reg_IR_ID[6:3] == 4'b0010 && reg_IR_ID[1:0] == 2'b11)                                                                                                          // xxxxxxxxxxxxxxxxxxx01xxxx0010x11
        || ( reg_IR_ID[12] == 1'b0 && reg_IR_ID[10] == 1'b1 && reg_IR_ID[6:3] == 4'b0010 && reg_IR_ID[1:0] == 2'b11)                                                                                     // xxxxxxxxxxxxxxxxxxx0x1xxx0010x11
        || ( reg_IR_ID[12] == 1'b0 && reg_IR_ID[9] == 1'b1 && reg_IR_ID[6:3] == 4'b0010 && reg_IR_ID[1:0] == 2'b11)                                                                                      // xxxxxxxxxxxxxxxxxxx0xx1xx0010x11
        || ( reg_IR_ID[12] == 1'b0 && reg_IR_ID[8] == 1'b1 && reg_IR_ID[6:3] == 4'b0010 && reg_IR_ID[1:0] == 2'b11)                                                                                      // xxxxxxxxxxxxxxxxxxx0xxx1x0010x11
        || ( reg_IR_ID[12] == 1'b0 && reg_IR_ID[7:3] == 5'b10010 && reg_IR_ID[1:0] == 2'b11)                                                                                                             // xxxxxxxxxxxxxxxxxxx0xxxx10010x11
        || ( reg_IR_ID[11] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b10111)                                                                                                                // xxxxxxxxxxxxxxxxxxxx1xxxx0x10111
        || ( reg_IR_ID[11] == 1'b1 && reg_IR_ID[6:0] == 7'b1101111)                                                                                                                                      // xxxxxxxxxxxxxxxxxxxx1xxxx1101111
        || ( reg_IR_ID[10] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b10111)                                                                                                                // xxxxxxxxxxxxxxxxxxxxx1xxx0x10111
        || ( reg_IR_ID[10] == 1'b1 && reg_IR_ID[6:0] == 7'b1101111)                                                                                                                                      // xxxxxxxxxxxxxxxxxxxxx1xxx1101111
        || ( reg_IR_ID[9] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b10111)                                                                                                                 // xxxxxxxxxxxxxxxxxxxxxx1xx0x10111
        || ( reg_IR_ID[9] == 1'b1 && reg_IR_ID[6:0] == 7'b1101111)                                                                                                                                       // xxxxxxxxxxxxxxxxxxxxxx1xx1101111
        || ( reg_IR_ID[8] == 1'b1 && reg_IR_ID[6] == 1'b0 && reg_IR_ID[4:0] == 5'b10111)                                                                                                                 // xxxxxxxxxxxxxxxxxxxxxxx1x0x10111
        || ( reg_IR_ID[8] == 1'b1 && reg_IR_ID[6:0] == 7'b1101111)                                                                                                                                       // xxxxxxxxxxxxxxxxxxxxxxx1x1101111
        || ( reg_IR_ID[7:6] == 2'b10 && reg_IR_ID[4:0] == 5'b10111)                                                                                                                                      // xxxxxxxxxxxxxxxxxxxxxxxx10x10111
        || ( reg_IR_ID[7:0] == 8'b11101111)                                                                                                                                                              // xxxxxxxxxxxxxxxxxxxxxxxx11101111
         )
      begin
        en_hazards_decode_EX = 1'b1; // jalr_readHWraw1stEX  t5u_cstP7_EX[regX.n:99][cnn.n:35]
                                     // agu_read_after_writeHWraw1stEX  t5u_cstP7_EX[regX.n:99][cnn.n:35]
      end
    end
    predec_EX_enabling[3:0] = en_alu_bin_sel_EX;
    predec_EX_enabling[6:4] = en_cmp_bin_sel_EX;
    predec_EX_enabling[7] = en_divR_divs_divA_divB_div_EX;
    predec_EX_enabling[8] = en_divR_divu_divA_divB_div_EX;
    predec_EX_enabling[9] = en_divR_rems_divA_divB_div_EX;
    predec_EX_enabling[10] = en_divR_remu_divA_divB_div_EX;
    predec_EX_enabling[13:11] = en_lx_bin_sel_EX;
    predec_EX_enabling[14] = en_mpy_ohe_sel_EX;
    predec_EX_enabling[15] = en_cnn_ohe_sel_EX;
    predec_EX_enabling[16] = en_controller_ohe_sel_EX;
    predec_EX_enabling[18:17] = en_reg_X_bin_sel_EX;
    predec_EX_enabling[21:19] = en_mem_DMb_bin_sel_EX;
    predec_EX_enabling[22] = en_mux_dmb_wr_ohe_sel_EX;
    predec_EX_enabling[25:23] = en_mux_x_w1_bin_sel_EX;
    predec_EX_enabling[26] = en_mux_x_w1_dead_ohe_sel_EX;
    predec_EX_enabling[27] = en_mux_aluA_ohe_sel_EX;
    predec_EX_enabling[29:28] = en_mux_aluB_bin_sel_EX;
    predec_EX_enabling[31:30] = en_mux_mpyM_bin_sel_EX;
    predec_EX_enabling[32] = en_mux_ocd_swbreak_ohe_sel_EX;
    predec_EX_enabling[33] = en_mux___X_x_w1_wad_ohe_sel_EX;
    predec_EX_enabling[34] = en_hazards_decode_EX;
  end

  always @ (posedge clock or posedge reset)
  begin : ID_stage_start
    if (reset)
    begin
      reg_ID_valid <= 1'b0;
      reg_IR_ID <= NOP;
    end
    else
    begin
      if (!hzd_stall_in || trn_ID_valid_in || kill_ID_in)
      begin
        reg_ID_valid <= trn_ID_valid_in;
        reg_IR_ID <= trn_IR_ID;
      end
    end
  end

  assign ID_enabling = predec_ID_enabling;

  assign trn_EX_valid = reg_ID_valid && !kill_ID_in && !hzd_stall_in;

  always @ (posedge clock or posedge reset)
  begin : EX_stage_start
    if (reset)
    begin
      reg_IR_EX <= NOP;
      EX_enabling <= 0;
    end
    else
    begin
      reg_IR_EX <= reg_IR_ID;
      EX_enabling <= predec_EX_enabling;
    end
  end

  always @ (posedge clock or posedge reset)
  begin : p___X_x_r1_raddr
    if (reset)
    begin
      r___X_x_r1_raddr <= 0;
    end
    else
    begin
      if (en___X_x_r1_raddr_EX)
        r___X_x_r1_raddr <= __X_x_r1_raddr_EX;
    end
  end

  assign __X_x_r1_rad_out = r___X_x_r1_raddr; // __X_x_r1_raddr

  always @ (posedge clock or posedge reset)
  begin : p___X_x_r2_raddr
    if (reset)
    begin
      r___X_x_r2_raddr <= 0;
    end
    else
    begin
      if (en___X_x_r2_raddr_EX)
        r___X_x_r2_raddr <= __X_x_r2_raddr_EX;
    end
  end

  assign __X_x_r2_rad_out = r___X_x_r2_raddr; // __X_x_r2_raddr

  always @ (posedge clock or posedge reset)
  begin : p___X_x_r3_raddr
    if (reset)
    begin
      r___X_x_r3_raddr <= 0;
    end
    else
    begin
      if (en___X_x_r3_raddr_EX)
        r___X_x_r3_raddr <= __X_x_r3_raddr_EX;
      else if (en___X_x_r3_raddr_ID)
        r___X_x_r3_raddr <= __X_x_r3_raddr_ID;
    end
  end

  assign __X_x_r3_rad_out = en___X_x_r3_raddr_ID ? __X_x_r3_raddr_ID :
    r___X_x_r3_raddr; // __X_x_r3_raddr

  always @ (posedge clock or posedge reset)
  begin : p___X_x_w2_waddr
    if (reset)
    begin
      r___X_x_w2_waddr <= 0;
    end
    else
    begin
      if (en___X_x_w2_waddr_EX)
        r___X_x_w2_waddr <= __X_x_w2_waddr_EX;
    end
  end

  assign __X_x_w2_wad_out = r___X_x_w2_waddr; // __X_x_w2_waddr

endmodule
